---
output:
  html_document: default
  pdf_document: default
---
# Text solutions

## Chapter 1

***Example 1.1:*** \
Population: all season passing totals of Manning's career \
Sample: season passing totals of Manning's career with Broncos

***Example 1.2:*** \
Discrete: Passing yards, Passing TDs \
Continuous: Passing attempt release times, Average yards per pass by game

***Example 1.3:*** \
Nominal: Pass result (completion, incomplete, interception) \
Ordinal: Season injury status (no injuries, some injuries, missed full year)

***Example 1.4:*** \
$(4659 + 5477 + 4727 + 2249)/4 = 4278$

***Example 1.5:*** \
Colts ordered data: 3739, 3747, 4002, 4040, 4131, 4135, **4200**, 4267, 4397, 4413, 4500, 4557, 4700
Broncos ordered data: 2249, 4659, 4727, 5477 $\to (4659+4727)/2 = 4693$

***Example 1.6:*** \
Wins: 12, Games: 16, p=12/16=0.75

***Example 3.8*** \
(a) $AB = PA - BB - HBP - SF = 664 - 177 - 9 - 2 = 476$ \
(b) $P(Hit) = AVG = 156 / 664 = 0.328$ \
(c) $P(\text{reach first}) = OBA = (156+177+9)/664 = 0.515$ \
(d) $P(\text{didn't reach first}) = 1 - OBA = 0.485$ \
(e) $P(HBP \cup BB) = (177+9)/664 = 0.280 $ \
(f) $P(HBP^C \cap BB^C) = P[(HBP \cup BB)^C] = 1- P(HBP \cup BB) = 0.720$ \

***Example 3.9*** \
(a) $P(HR) = 66/722 = 0.0914$ \
(b) $P(HR \cap June) = 20/722 = 0.0277$ \
(c) $P(June) = 121/722 = 0.1676$ \
(d) $P(HR|June) = 0.1653$ \ 
(e) $P(June|HR) = 20/66 = 0.3030$ \
(f) $P(HR|June^c) = (66-20)/(722-121) = 0.0765$ \

***Example 3.10**
$P(HR and June) = P(HR|June)P(June) = 0.167*0.168 = 0.028$ \

***Example 3.11**
June/Not June, April/May/June/July/August/Sept, Home/Road \

***Example 3.12***
$P(HR|June) = P(HR \, and \, June)/P(June) = 0.028/0.168 = 0.167$ \

***Example 3.13***
(a) $P(Goal) = P(G|H)*P(H)+P(G|R)*P(R) = 0.3*0.5 + 0.18*0.5 = 0.24$ \
(b) $P(G) = 2/3*0.3 + 1/3*0.18 = 0.26$ \
(c) $P(G) = 2/5*0.3 + 3/5*0.18 = 0.228$ \

***Example 3.14***
$9! = 362880$ \

***Example 3.15***
$13p9 = 259459200$ \

***Example 3.16***
$13c9 = 715$ \

***Example 3.17***
$13c9 * 13c1 = 715*13 = 9295$ \
