<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="2.8 Extra Stuff | Sports Analytics" />
<meta property="og:type" content="book" />
<meta property="og:image" content="https://aaron-nielsen.github.io/SportsAnalyticsBook/images/csu.png" />
<meta property="og:description" content="2.8 Extra Stuff | Sports Analytics Notes" />
<meta name="github-repo" content="aaron-nielsen.github.io/SportsAnalyticsBook/" />

<meta name="author" content="Aaron Nielsen, Department of Statistics, Colorado State University" />

<meta name="date" content="2022-07-21" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="2.8 Extra Stuff | Sports Analytics Notes">

<title>2.8 Extra Stuff | Sports Analytics</title>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if boostrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#about">About</a></li>
<li class="has-sub"><a href="1-exploratory-data-analysis.html#exploratory-data-analysis"><span class="toc-section-number">1</span> Exploratory Data Analysis</a>
<ul>
<li class="has-sub"><a href="1.1-getting-started-with-r.html#getting-started-with-r"><span class="toc-section-number">1.1</span> Getting Started With R</a>
<ul>
<li><a href="1.1-getting-started-with-r.html#installing-r"><span class="toc-section-number">1.1.1</span> Installing R</a></li>
<li><a href="1.1-getting-started-with-r.html#some-r-basics"><span class="toc-section-number">1.1.2</span> Some R Basics</a></li>
</ul></li>
<li class="has-sub"><a href="1.2-descriptive-statistics.html#descriptive-statistics"><span class="toc-section-number">1.2</span> Descriptive Statistics</a>
<ul>
<li><a href="1.2-descriptive-statistics.html#definitions"><span class="toc-section-number">1.2.1</span> Definitions</a></li>
<li><a href="1.2-descriptive-statistics.html#descriptive-statistics-1"><span class="toc-section-number">1.2.2</span> Descriptive Statistics</a></li>
</ul></li>
<li class="has-sub"><a href="1.3-visualizations.html#visualizations"><span class="toc-section-number">1.3</span> Visualizations</a>
<ul>
<li><a href="1.3-visualizations.html#histograms"><span class="toc-section-number">1.3.1</span> Histograms</a></li>
<li><a href="1.3-visualizations.html#bar-plots"><span class="toc-section-number">1.3.2</span> Bar Plots</a></li>
<li><a href="1.3-visualizations.html#scatter-plots"><span class="toc-section-number">1.3.3</span> Scatter Plots</a></li>
<li><a href="1.3-visualizations.html#kable-tables"><span class="toc-section-number">1.3.4</span> Kable Tables</a></li>
</ul></li>
<li class="has-sub"><a href="1.4-baseball.html#baseball"><span class="toc-section-number">1.4</span> Baseball</a>
<ul>
<li><a href="1.4-baseball.html#basic-hitting-statistics"><span class="toc-section-number">1.4.1</span> Basic Hitting Statistics</a></li>
<li><a href="1.4-baseball.html#basic-pitching-statistics"><span class="toc-section-number">1.4.2</span> Basic Pitching Statistics</a></li>
<li><a href="1.4-baseball.html#advanced-baseball-hitting-statistics"><span class="toc-section-number">1.4.3</span> Advanced Baseball Hitting Statistics</a></li>
<li><a href="1.4-baseball.html#advanced-baseball-pitching-statistics"><span class="toc-section-number">1.4.4</span> Advanced Baseball Pitching Statistics</a></li>
<li><a href="1.4-baseball.html#wins-above-replacement"><span class="toc-section-number">1.4.5</span> Wins Above Replacement</a></li>
<li><a href="1.4-baseball.html#calculating-advanced-hitting-statistics"><span class="toc-section-number">1.4.6</span> Calculating Advanced Hitting Statistics</a></li>
<li><a href="1.4-baseball.html#evaluating-advanced-pitching-statistics"><span class="toc-section-number">1.4.7</span> Evaluating Advanced Pitching Statistics</a></li>
</ul></li>
<li class="has-sub"><a href="1.5-football.html#football"><span class="toc-section-number">1.5</span> Football</a>
<ul>
<li><a href="1.5-football.html#basic-football-statistics"><span class="toc-section-number">1.5.1</span> Basic Football Statistics</a></li>
<li><a href="1.5-football.html#advanced-football-statistics"><span class="toc-section-number">1.5.2</span> Advanced Football Statistics</a></li>
</ul></li>
<li class="has-sub"><a href="1.6-basketball.html#basketball"><span class="toc-section-number">1.6</span> Basketball</a>
<ul>
<li><a href="1.6-basketball.html#basic-basketball-statistics"><span class="toc-section-number">1.6.1</span> Basic Basketball Statistics</a></li>
<li><a href="1.6-basketball.html#advanced-basketball-statistics"><span class="toc-section-number">1.6.2</span> Advanced Basketball Statistics</a></li>
<li><a href="1.6-basketball.html#four-factors"><span class="toc-section-number">1.6.3</span> Four Factors</a></li>
<li><a href="1.6-basketball.html#shot-charts"><span class="toc-section-number">1.6.4</span> Shot Charts</a></li>
</ul></li>
<li class="has-sub"><a href="1.7-hockey.html#hockey"><span class="toc-section-number">1.7</span> Hockey</a>
<ul>
<li><a href="1.7-hockey.html#basic-hockey-statistics"><span class="toc-section-number">1.7.1</span> Basic Hockey Statistics</a></li>
<li><a href="1.7-hockey.html#advanced-hockey-statistics"><span class="toc-section-number">1.7.2</span> Advanced Hockey Statistics</a></li>
<li><a href="1.7-hockey.html#actual-vs.-expected-goals"><span class="toc-section-number">1.7.3</span> Actual vs. Expected Goals</a></li>
<li><a href="1.7-hockey.html#goalie-statistics"><span class="toc-section-number">1.7.4</span> Goalie Statistics</a></li>
<li><a href="1.7-hockey.html#correlation-plots"><span class="toc-section-number">1.7.5</span> Correlation Plots</a></li>
</ul></li>
<li class="has-sub"><a href="1.8-volleyball.html#volleyball"><span class="toc-section-number">1.8</span> Volleyball</a>
<ul>
<li><a href="1.8-volleyball.html#basic-volleyball-statistics"><span class="toc-section-number">1.8.1</span> Basic Volleyball Statistics</a></li>
<li><a href="1.8-volleyball.html#scatter-plot"><span class="toc-section-number">1.8.2</span> Scatter Plot</a></li>
<li><a href="1.8-volleyball.html#box-plot"><span class="toc-section-number">1.8.3</span> Box Plot</a></li>
</ul></li>
<li class="has-sub"><a href="1.9-soccer.html#soccer"><span class="toc-section-number">1.9</span> Soccer</a>
<ul>
<li><a href="1.9-soccer.html#basic-soccer-statistics"><span class="toc-section-number">1.9.1</span> Basic Soccer Statistics</a></li>
<li><a href="1.9-soccer.html#advanced-soccer-statistics"><span class="toc-section-number">1.9.2</span> Advanced Soccer Statistics</a></li>
<li><a href="1.9-soccer.html#bar-plot"><span class="toc-section-number">1.9.3</span> Bar Plot</a></li>
<li><a href="1.9-soccer.html#scatter-plot-1"><span class="toc-section-number">1.9.4</span> Scatter Plot</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="2-probability.html#probability"><span class="toc-section-number">2</span> Probability</a>
<ul>
<li><a href="chapter-preview.html#chapter-preview">Chapter Preview</a></li>
<li><a href="2.1-definitions-1.html#definitions-1"><span class="toc-section-number">2.1</span> Definitions</a></li>
<li><a href="2.2-set-theory.html#set-theory"><span class="toc-section-number">2.2</span> Set Theory</a></li>
<li class="has-sub"><a href="2.3-axioms-properties-and-laws.html#axioms-properties-and-laws"><span class="toc-section-number">2.3</span> Axioms, Properties, and Laws</a>
<ul>
<li><a href="2.3-axioms-properties-and-laws.html#axioms-of-probability"><span class="toc-section-number">2.3.1</span> Axioms of Probability</a></li>
<li><a href="2.3-axioms-properties-and-laws.html#properties-of-probability"><span class="toc-section-number">2.3.2</span> Properties of Probability</a></li>
<li><a href="2.3-axioms-properties-and-laws.html#laws-of-probability"><span class="toc-section-number">2.3.3</span> Laws of Probability</a></li>
</ul></li>
<li><a href="2.4-combinatorics.html#combinatorics"><span class="toc-section-number">2.4</span> Combinatorics</a></li>
<li class="has-sub"><a href="2.5-odds-and-gambling.html#odds-and-gambling"><span class="toc-section-number">2.5</span> Odds and Gambling</a>
<ul>
<li><a href="2.5-odds-and-gambling.html#sports-betting-in-usa"><span class="toc-section-number">2.5.1</span> Sports Betting in USA</a></li>
<li><a href="2.5-odds-and-gambling.html#gambling-addiction"><span class="toc-section-number">2.5.2</span> Gambling Addiction</a></li>
<li><a href="2.5-odds-and-gambling.html#odds-definition"><span class="toc-section-number">2.5.3</span> Odds Definition</a></li>
<li><a href="2.5-odds-and-gambling.html#gambling-odds"><span class="toc-section-number">2.5.4</span> Gambling Odds</a></li>
</ul></li>
<li><a href="2.6-random-variables.html#random-variables"><span class="toc-section-number">2.6</span> Random Variables</a></li>
<li class="has-sub"><a href="2.7-common-random-variables.html#common-random-variables"><span class="toc-section-number">2.7</span> Common Random Variables</a>
<ul>
<li><a href="2.7-common-random-variables.html#binomial-rvs"><span class="toc-section-number">2.7.1</span> Binomial RVs</a></li>
<li><a href="2.7-common-random-variables.html#geometric-rvs"><span class="toc-section-number">2.7.2</span> Geometric RVs</a></li>
<li><a href="2.7-common-random-variables.html#poisson-rvs"><span class="toc-section-number">2.7.3</span> Poisson RVs</a></li>
<li><a href="2.7-common-random-variables.html#negative-binomial-rvs"><span class="toc-section-number">2.7.4</span> Negative Binomial RVs</a></li>
<li><a href="2.7-common-random-variables.html#normal-rvs"><span class="toc-section-number">2.7.5</span> Normal RVs</a></li>
</ul></li>
<li class="has-sub"><a href="2.8-extra-stuff.html#extra-stuff"><span class="toc-section-number">2.8</span> Extra Stuff</a>
<ul>
<li><a href="2.8-extra-stuff.html#sets-and-conditional-probability"><span class="toc-section-number">2.8.1</span> Sets and Conditional Probability</a></li>
<li><a href="2.8-extra-stuff.html#binomials-and-multinomials"><span class="toc-section-number">2.8.2</span> Binomials and Multinomials</a></li>
<li><a href="2.8-extra-stuff.html#expectation---baseball"><span class="toc-section-number">2.8.3</span> Expectation - Baseball</a></li>
<li><a href="2.8-extra-stuff.html#basketball-scenario"><span class="toc-section-number">2.8.4</span> Basketball Scenario</a></li>
<li><a href="2.8-extra-stuff.html#multiple-probability-distributions---basketball"><span class="toc-section-number">2.8.5</span> Multiple Probability Distributions - Basketball</a></li>
<li><a href="2.8-extra-stuff.html#law-of-total-probability---baseball"><span class="toc-section-number">2.8.6</span> Law of Total Probability - Baseball</a></li>
<li><a href="2.8-extra-stuff.html#multinomial-distribution---baseball"><span class="toc-section-number">2.8.7</span> Multinomial Distribution - Baseball</a></li>
<li><a href="2.8-extra-stuff.html#bayes---injured-baseball-player"><span class="toc-section-number">2.8.8</span> Bayes - injured baseball player</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="3-monte-carlo-simulation.html#monte-carlo-simulation"><span class="toc-section-number">3</span> Monte Carlo Simulation</a>
<ul>
<li><a href="3.1-basics.html#basics"><span class="toc-section-number">3.1</span> Basics</a></li>
<li><a href="3.2-estimating-probabilities.html#estimating-probabilities"><span class="toc-section-number">3.2</span> Estimating Probabilities</a></li>
<li class="has-sub"><a href="3.3-simulating-streaks.html#simulating-streaks"><span class="toc-section-number">3.3</span> Simulating Streaks</a>
<ul>
<li><a href="3.3-simulating-streaks.html#winning-streak-simulation"><span class="toc-section-number">3.3.1</span> Winning Streak Simulation</a></li>
<li><a href="3.3-simulating-streaks.html#hitting-streak-simulation"><span class="toc-section-number">3.3.2</span> Hitting Streak Simulation</a></li>
</ul></li>
<li class="has-sub"><a href="3.4-gambling-simulations.html#gambling-simulations"><span class="toc-section-number">3.4</span> Gambling Simulations</a>
<ul>
<li><a href="3.4-gambling-simulations.html#martingale-system"><span class="toc-section-number">3.4.1</span> Martingale System</a></li>
</ul></li>
<li class="has-sub"><a href="3.5-extra-stuff-1.html#extra-stuff-1"><span class="toc-section-number">3.5</span> Extra stuff</a>
<ul>
<li><a href="3.5-extra-stuff-1.html#shaq-ft-simulation"><span class="toc-section-number">3.5.1</span> Shaq FT simulation</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="4-statistical-inference.html#statistical-inference"><span class="toc-section-number">4</span> Statistical Inference</a>
<ul>
<li><a href="4.1-one-sample-and-two-sample-t-tests-and-confidence-intervals.html#one-sample-and-two-sample-t-tests-and-confidence-intervals"><span class="toc-section-number">4.1</span> One Sample and Two Sample t-tests and confidence intervals</a></li>
</ul></li>
<li class="has-sub"><a href="5-correlation.html#correlation"><span class="toc-section-number">5</span> Correlation</a>
<ul>
<li class="has-sub"><a href="5.1-pearsons-correlation-coefficient.html#pearsons-correlation-coefficient"><span class="toc-section-number">5.1</span> Pearson’s Correlation Coefficient</a>
<ul>
<li><a href="5.1-pearsons-correlation-coefficient.html#properties-of-the-linear-correlation-coefficient"><span class="toc-section-number">5.1.1</span> Properties of the Linear Correlation Coefficient</a></li>
</ul></li>
<li><a href="5.2-rank-correlation.html#rank-correlation"><span class="toc-section-number">5.2</span> Rank Correlation</a></li>
<li><a href="5.3-autocorrelation.html#autocorrelation"><span class="toc-section-number">5.3</span> Autocorrelation</a></li>
<li><a href="5.4-association-of-categorical-variables.html#association-of-categorical-variables"><span class="toc-section-number">5.4</span> Association of Categorical Variables</a></li>
</ul></li>
<li class="has-sub"><a href="6-linear-regression.html#linear-regression"><span class="toc-section-number">6</span> Linear Regression</a>
<ul>
<li><a href="6.1-simple-linear-regression.html#simple-linear-regression"><span class="toc-section-number">6.1</span> Simple Linear Regression</a></li>
<li><a href="6.2-multiple-linear-regression.html#multiple-linear-regression"><span class="toc-section-number">6.2</span> Multiple Linear Regression</a></li>
<li><a href="6.3-confounding-variables.html#confounding-variables"><span class="toc-section-number">6.3</span> Confounding Variables</a></li>
</ul></li>
<li><a href="references.html#references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="extra-stuff" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> Extra Stuff</h2>
<div id="sets-and-conditional-probability" class="section level3" number="2.8.1">
<h3><span class="header-section-number">2.8.1</span> Sets and Conditional Probability</h3>
<p>100 sports fans in Colorado were polled and it was found that 64 had attended either a Denver Nuggets or Colorado Avalanche game at Ball Arena (formerly Pepsi Center). 34 people had seen only a Nuggets game, while 17 had seen both a Nuggets and an Avalanche game.</p>
<p>Q: How many people saw an Avalanche game but not a Nuggets game?</p>
<p>A: 64 - 34 - 17 = 13</p>
<p>Q: What is the probability that a randomly selected person in the poll had been to a Nuggets game?</p>
<p>A: (34 + 17) / 100 = .51</p>
<p>Q: What is the probability that a randomly selected person that had been to a game at Ball Arena had been to a Nuggets game?</p>
<p>A: (34 + 17) / 64 = .797</p>
<p>Q: What is the probability that a randomly selected person had been to a Nuggets game given they had been to an Avalanche game?</p>
<p>A: 17 / (17 + 13) = .567</p>
</div>
<div id="binomials-and-multinomials" class="section level3" number="2.8.2">
<h3><span class="header-section-number">2.8.2</span> Binomials and Multinomials</h3>
<p>Suppose we are curious about probabilities regarding the results of a soccer team’s next five games.</p>
<p>Wait!!! A soccer game has three possible outcomes (win, lose, draw)! We can’t use the binomial distribution, since it limits us to two possible outcomes!</p>
<p>It depends. If we are interested in the probability that a soccer team wins 2 of their next 5 games, we can use the binomial distribution. We can create the following partition of the sample space of outcomes: <span class="math inline">\((Win)\)</span> and <span class="math inline">\((Win^C)\)</span>, where the second set includes both losing and drawing.</p>
<p>Then, the formula would be represented as:</p>
<p><span class="math inline">\(\binom{5}{2}\ P(Win)^2\  P(Win^C)^{(5-2)}\)</span></p>
<p>If we are interested in the probability of the team winning two of the next five games, drawing two, and losing one, we cannot use the binomial theorem. That involves three outcomes, and would be represented as a multinomial. <!--- assuming regularity conditions such as independence. --></p>
</div>
<div id="expectation---baseball" class="section level3" number="2.8.3">
<h3><span class="header-section-number">2.8.3</span> Expectation - Baseball</h3>
<p>The expectation of a discrete random variable is a weighted average. The “weights” are the probabilities of the possible values of the variable.</p>
<p>Consider the following table, which shows the number of career hits by type for the all-time Major League Baseball leader in total bases, Hank Aaron.</p>
<!-- https://www.baseball-reference.com/players/a/aaronha01.shtml -->
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Hit_type
</th>
<th style="text-align:right;">
Number_bases
</th>
<th style="text-align:right;">
Hit_Frequency
</th>
<th style="text-align:right;">
Hit_Proportion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Single
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2294
</td>
<td style="text-align:right;">
0.6083267
</td>
</tr>
<tr>
<td style="text-align:left;">
Double
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
624
</td>
<td style="text-align:right;">
0.1654734
</td>
</tr>
<tr>
<td style="text-align:left;">
Triple
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
98
</td>
<td style="text-align:right;">
0.0259878
</td>
</tr>
<tr>
<td style="text-align:left;">
Home Run
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
755
</td>
<td style="text-align:right;">
0.2002122
</td>
</tr>
</tbody>
</table>
<p>The expected number of bases for a Hank Aaron hit is the sum of the number of bases attained for each hit multiplied by the relative frequency of the occurrence of that type of hit.</p>
<p><span class="math inline">\(1 \cdot \frac{2294}{3771} + 2 \cdot \frac{624}{3771} + 3 \cdot \frac{98}{3771} + 4 \cdot \frac{755}{3771} = 1.18181\)</span></p>
<p>This is the same process that is occurring whenever we calculate the expectation of any discrete random variable. Recall the formula for expectation is <span class="math inline">\(E[X] = \sum_{x \in \Omega}\ x \cdot p(x)\)</span>. Each value in the sample space is “adjusted” by the probability of that value, then the sum of all values in <span class="math inline">\(\Omega\)</span> is taken to arrive at the weighted average, or expected value, of the random variable.</p>
</div>
<div id="basketball-scenario" class="section level3" number="2.8.4">
<h3><span class="header-section-number">2.8.4</span> Basketball Scenario</h3>
<p>You are the coach of a basketball team that is down two points with one second remaining in the fourth quarter. During a timeout, you are considering the best play to call for your team. The first option is a three-point shot attempt, which you estimate has a 30% chance of succeeding. The second option is a two-point shot attempt, which has a 50% chance of making the field goal, a 30% chance of missing it and ending the game, and a 20% chance the shooter will miss but be fouled, in which case the shooter’s free throw success will follow a <span class="math inline">\(Bin(2, .8)\)</span> random variable. Finally, you estimate that your team’s probability of winning the game in overtime is .45.</p>
<p>Assume the above situations are exhaustive (i.e., the other team will not get another possession, no fouls will be called before the ball is put in play, lightning will not hit the arena and postpone the game, etc.). Which of the two plays should you call to maximize the win probability for your team?</p>
<p>A: The probability of winning the game with the three-point shot attempt is .3. If the two-point shot attempt is called for, there is a .5 probability of making the field goal and a (.2)(.8)(.8) = .128 probability that the foul is called and both free throws are made. Thus, the total probability of scoring two points and sending the game to overtime is .628. Then, the probability of winning the game in OT after tying it in regulation is (.628)(.45) = .2828. This is less than .3, so shooting the three-pointer is the option that maximizes the win probability, given these situational probabilities.</p>
<p>Q: What is the minimum estimated overtime win probability to make calling for the two-point play the better option?</p>
<p>A: <span class="math inline">\(P(score\ 2\ points\ in\ regulation) \cdot P(win\ in\ OT) &gt; P(win\ in\ regulation)\)</span><br />
<span class="math inline">\(.628 \cdot P(win\ in\ OT) &gt; .3\)</span><br />
<span class="math inline">\(P(win\ in\ OT) &gt; .478\)</span></p>
</div>
<div id="multiple-probability-distributions---basketball" class="section level3" number="2.8.5">
<h3><span class="header-section-number">2.8.5</span> Multiple Probability Distributions - Basketball</h3>
<p>Suppose the number of points scored by a basketball player follows a Poisson(12) random variable, the number of rebounds by a Poisson(7) distribution, and assists by a Discrete Uniform(2, 11), independently of each other.</p>
<p>Q: What is the probability that this player records a points, rebounds, assists triple-double in a game?</p>
<p>A: <span class="math inline">\(P(Triple\ Double) = P(Points \geq 10\ \cap\ Rebounds \geq 10\ \cap\ Assists \geq 10)\)</span></p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="2.8-extra-stuff.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ppois</span>(<span class="dv">9</span>, <span class="at">lambda =</span> <span class="dv">12</span>, <span class="at">lower.tail=</span>F)</span></code></pre></div>
<pre><code>## [1] 0.7576078</code></pre>
<p><span class="math inline">\(P(Points \geq 10) = P(Poisson(12) \geq 10) \approx .758\)</span></p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="2.8-extra-stuff.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ppois</span>(<span class="dv">9</span>, <span class="at">lambda =</span> <span class="dv">7</span>, <span class="at">lower.tail=</span>F)</span></code></pre></div>
<pre><code>## [1] 0.1695041</code></pre>
<p><span class="math inline">\(P(Rebounds \geq 10) = P(Poisson(7) \geq 10) \approx .170\)</span></p>
<p><span class="math inline">\(P(Assists \geq 10) = P(Discrete\ Uniform(2, 11) \geq 10) = .2\)</span></p>
<p>Since the events are independent, we can multiply their probabilities. The probability of the player scoring the triple-double is <span class="math inline">\((.758)(.170)(.2) = .0257\)</span>.</p>
<p>Q: Your friend offers you 4 to 1 that the player will not record a triple-double in their next 10 games. With the knowledge that the athlete’s performance in a game is unaffected by performances in previous games, would you take the bet?</p>
<p>A: <span class="math inline">\(P(no\ triple\ double) = 1 - .0257 = .9743\)</span>, so <span class="math inline">\(P(no\ triple\ double\ in\ next\ 10\ games) = (.9743)^{10} = .771\)</span></p>
<p>The odds of no triple-double are <span class="math inline">\(\frac{.771}{1-.771} = 3.37\)</span>, so the bet of no triple-double at 4 to 1 odds is favorable.</p>
<p><em>answers may vary for following questions</em></p>
<p>Q: What differences do you notice between the actual results and the expected values based on the Poisson random variable?</p>
<p>A: There were fewer games in which the Rapids scored 4 or more goals than the model would indicate, yet the Rapids were shut out less often than the model would indicate.</p>
<p>Q: Even if the true population distribution of 2021 Rapids goals was truly a Poisson(1.5) random variable, why might the actual distribution of their goals differ from the probability mass function?</p>
<p>A: 34 is a relatively small sample size; random variables may not coincide with their expected values for finite sample sizes.</p>
<p>Q: What are the advantages of using the Poisson distribution to model Major League soccer goals? What are the disadvantages?</p>
<p>A: Poisson random variables can take on the natural numbers (including zero), which aligns with the number of goals that can be scored in a match. One disadvantage is that it is possible for a Poisson to take on values that are not realistic for the situation, such as double-digit integers or higher. Only one game in MLS history has had a team score more than seven goals in a game. However, when <span class="math inline">\(\lambda\)</span> is small (such as 1.5), these extreme values are relatively unlikely.</p>
</div>
<div id="law-of-total-probability---baseball" class="section level3" number="2.8.6">
<h3><span class="header-section-number">2.8.6</span> Law of Total Probability - Baseball</h3>
<p>You work in the front office of a professional baseball club and have just learned that a certain prospect hits .200 against left-handed pitchers and .400 against right-handed pitchers (their overall batting average is unknown). The general manager of the team overhears you talking about the .400 statistic of the player and becomes very exited that they have the chance to draft a .400 hitter. What would you say to caution the GM that the player might not be a remarkable hitter?</p>
<p>A: We don’t know the proportion of the player’s at-bats that came against left-handed pitchers versus right-handed pitchers. If we want to know the player’s batting average unconditional on the type of pitcher they are facing, we have to adjust <span class="math inline">\(P(hit\ |\ left-handed\ pitcher)\)</span> by <span class="math inline">\(P(left-handed\ pitcher)\)</span> and <span class="math inline">\(P(hit\ |\ right-handed\ pitcher)\)</span> by <span class="math inline">\(P(right-handed\ pitcher)\)</span> before adding them to determine <span class="math inline">\(P(hit)\)</span>. For example, if 90% of the player’s at-bats were against left-handed pitchers, then their overall batting average is a pedestrian .220.</p>
<p><em>Other possible issues: low sample size of player’s at-bats, the fact that pro pitchers will be harder to hit against than non-pros</em></p>
</div>
<div id="multinomial-distribution---baseball" class="section level3" number="2.8.7">
<h3><span class="header-section-number">2.8.7</span> Multinomial Distribution - Baseball</h3>
<p>The following PMF displays the number of possible bases for a hit in baseball against the frequency of that type of hit for Hank Aaron, who is third all-time in Major League baseball hits with 3,771.</p>
<table>
<thead>
<tr class="header">
<th align="center">Number of Bases, <span class="math inline">\(x\)</span></th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Probability, <span class="math inline">\(P(X=x)\)</span></td>
<td align="center">0.61</td>
<td align="center">0.16</td>
<td align="center">0.03</td>
<td align="center">0.20</td>
</tr>
</tbody>
</table>
<p>Q: What is the probability that a randomly selected subset of 5 hits from Hank Aaron includes three singles, one double, and one home run?</p>
<!-- note: assumes sampling with replacement. Without replacement would be a multivariate hypergeometric and would slightly increase the probability.  -->
<p>A: From the Multinomial PMF, this is <span class="math inline">\(P(X_1 = 3, X_2 = 1, X_3 = 0, X_4 = 1) = \frac{5!}{3!\ \cdot 1!\ \cdot 0!\ \cdot 1!}\ (.61)^3\cdot\ (.16)^1\cdot\ (.03)^0\cdot\ (.20)^1 \approx .145\)</span></p>
<p>The probability can also be found in <code>R</code> using the <code>dmultinom</code> function.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="2.8-extra-stuff.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dmultinom</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">prob =</span> <span class="fu">c</span>(.<span class="dv">61</span>, .<span class="dv">16</span>, .<span class="dv">03</span>, .<span class="dv">20</span>))</span></code></pre></div>
<pre><code>## [1] 0.1452678</code></pre>
</div>
<div id="bayes---injured-baseball-player" class="section level3" number="2.8.8">
<h3><span class="header-section-number">2.8.8</span> Bayes - injured baseball player</h3>
<div class="example">
<p><span id="exm:unlabeled-div-117" class="example"><strong>Example 2.42  </strong></span>A runner on first base with 2 out and nobody else on base will attempt to steal second base on the first pitch 70% of the time if he is fully healthy but only 10% of the time if he is playing through an injury. Assume that 80% of the player population is healthy. You see a randomly selected runner not attempt a steal in this situation. What is the probability that the runner is playing through an injury?</p>
</div>
<p>From Bayes Theorem:</p>
<p>Pr(Injury given No Steal) = Pr(No Steal given Injury)*Pr(Injury)/P(No Steal).</p>
<p>Pr(No Steal given Injury) = 1 - Pr(Steal given Injury) = 0.9.</p>
<p>Pr(Injury) = 1- Pr(Healthy) = 0.2.</p>
<p>Pr(No Steal) = Pr(No Steal given Injury)*Pr(Injury)+Pr(No Steal given Healthy)*Pr(Healthy).</p>
<p>Pr(No Steal) = 0.9*0.2+0.7*0.8 = 0.74.</p>
<p>Therefore Pr(Injury given No Steal) = 0.9*0.2/0.74 = 0.243.</p>

</div>
</div>
<!-- </div> -->
<p style="text-align: center;">
<a href="2.7-common-random-variables.html"><button class="btn btn-default">Previous</button></a>
<a href="3-monte-carlo-simulation.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
