<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Exploratory Data Analysis | Sports Analytics</title>
  <meta name="description" content="Chapter 1 Exploratory Data Analysis | Sports Analytics Notes" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Exploratory Data Analysis | Sports Analytics" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://aaron-nielsen.github.io/SportsAnalyticsBook/images/csu.png" />
  <meta property="og:description" content="Chapter 1 Exploratory Data Analysis | Sports Analytics Notes" />
  <meta name="github-repo" content="aaron-nielsen.github.io/SportsAnalyticsBook/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Exploratory Data Analysis | Sports Analytics" />
  
  <meta name="twitter:description" content="Chapter 1 Exploratory Data Analysis | Sports Analytics Notes" />
  <meta name="twitter:image" content="https://aaron-nielsen.github.io/SportsAnalyticsBook/images/csu.png" />

<meta name="author" content="Aaron Nielsen, Department of Statistics, Colorado State University" />


<meta name="date" content="2022-07-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="current-tasks.html"/>
<link rel="next" href="probability.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Sports Analytics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="" data-path="current-tasks.html"><a href="current-tasks.html"><i class="fa fa-check"></i>Current Tasks</a></li>
<li class="chapter" data-level="1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>1</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#getting-started-with-r"><i class="fa fa-check"></i><b>1.1</b> Getting Started With R</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#installing-r"><i class="fa fa-check"></i><b>1.1.1</b> Installing R</a></li>
<li class="chapter" data-level="1.1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#some-r-basics"><i class="fa fa-check"></i><b>1.1.2</b> Some R Basics</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.2</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#definitions"><i class="fa fa-check"></i><b>1.2.1</b> Definitions</a></li>
<li class="chapter" data-level="1.2.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#descriptive-statistics-1"><i class="fa fa-check"></i><b>1.2.2</b> Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#visualizations"><i class="fa fa-check"></i><b>1.3</b> Visualizations</a></li>
<li class="chapter" data-level="1.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#baseball"><i class="fa fa-check"></i><b>1.4</b> Baseball</a></li>
<li class="chapter" data-level="1.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#football"><i class="fa fa-check"></i><b>1.5</b> Football</a></li>
<li class="chapter" data-level="1.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#basketball"><i class="fa fa-check"></i><b>1.6</b> Basketball</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#basic-basketball-statistics"><i class="fa fa-check"></i><b>1.6.1</b> Basic Basketball Statistics</a></li>
<li class="chapter" data-level="1.6.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#advanced-basketball-statistics"><i class="fa fa-check"></i><b>1.6.2</b> Advanced Basketball Statistics</a></li>
<li class="chapter" data-level="1.6.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#four-factors"><i class="fa fa-check"></i><b>1.6.3</b> Four Factors</a></li>
<li class="chapter" data-level="1.6.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#basketballanalyzer-four-factors"><i class="fa fa-check"></i><b>1.6.4</b> BasketballAnalyzeR Four Factors</a></li>
<li class="chapter" data-level="1.6.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#basketballanalyzer-shot-charts"><i class="fa fa-check"></i><b>1.6.5</b> BasketballAnalyzeR Shot Charts</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#soccer"><i class="fa fa-check"></i><b>1.7</b> Soccer</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#bar-plot"><i class="fa fa-check"></i><b>1.7.1</b> Bar Plot</a></li>
<li class="chapter" data-level="1.7.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatter-plot"><i class="fa fa-check"></i><b>1.7.2</b> Scatter Plot</a></li>
<li class="chapter" data-level="1.7.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#density-ridges-plot"><i class="fa fa-check"></i><b>1.7.3</b> Density Ridges Plot</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#hockey"><i class="fa fa-check"></i><b>1.8</b> Hockey</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#basic-hockey-statistics"><i class="fa fa-check"></i><b>1.8.1</b> Basic Hockey Statistics</a></li>
<li class="chapter" data-level="1.8.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#advanced-hockey-statistics"><i class="fa fa-check"></i><b>1.8.2</b> Advanced Hockey Statistics</a></li>
<li class="chapter" data-level="1.8.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#actual-vs.-expected-goals"><i class="fa fa-check"></i><b>1.8.3</b> Actual vs. Expected Goals</a></li>
<li class="chapter" data-level="1.8.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#goalie-statistics"><i class="fa fa-check"></i><b>1.8.4</b> Goalie Statistics</a></li>
<li class="chapter" data-level="1.8.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#correlation-plots"><i class="fa fa-check"></i><b>1.8.5</b> Correlation Plots</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#volleyball"><i class="fa fa-check"></i><b>1.9</b> Volleyball</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#scatter-plot-1"><i class="fa fa-check"></i><b>1.9.1</b> Scatter Plot</a></li>
<li class="chapter" data-level="1.9.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#box-plot"><i class="fa fa-check"></i><b>1.9.2</b> Box Plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>2</b> Probability</a>
<ul>
<li class="chapter" data-level="" data-path="probability.html"><a href="probability.html#chapter-preview"><i class="fa fa-check"></i>Chapter Preview</a></li>
<li class="chapter" data-level="2.1" data-path="probability.html"><a href="probability.html#definitions-1"><i class="fa fa-check"></i><b>2.1</b> Definitions</a></li>
<li class="chapter" data-level="2.2" data-path="probability.html"><a href="probability.html#set-theory"><i class="fa fa-check"></i><b>2.2</b> Set Theory</a></li>
<li class="chapter" data-level="2.3" data-path="probability.html"><a href="probability.html#axioms-properties-and-laws"><i class="fa fa-check"></i><b>2.3</b> Axioms, Properties, and Laws</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="probability.html"><a href="probability.html#axioms-of-probability"><i class="fa fa-check"></i><b>2.3.1</b> Axioms of Probability</a></li>
<li class="chapter" data-level="2.3.2" data-path="probability.html"><a href="probability.html#properties-of-probability"><i class="fa fa-check"></i><b>2.3.2</b> Properties of Probability</a></li>
<li class="chapter" data-level="2.3.3" data-path="probability.html"><a href="probability.html#laws-of-probability"><i class="fa fa-check"></i><b>2.3.3</b> Laws of Probability</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="probability.html"><a href="probability.html#combinatorics"><i class="fa fa-check"></i><b>2.4</b> Combinatorics</a></li>
<li class="chapter" data-level="2.5" data-path="probability.html"><a href="probability.html#odds-and-gambling"><i class="fa fa-check"></i><b>2.5</b> Odds and Gambling</a></li>
<li class="chapter" data-level="2.6" data-path="probability.html"><a href="probability.html#random-variables"><i class="fa fa-check"></i><b>2.6</b> Random Variables</a></li>
<li class="chapter" data-level="2.7" data-path="probability.html"><a href="probability.html#common-random-variables"><i class="fa fa-check"></i><b>2.7</b> Common Random Variables</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="probability.html"><a href="probability.html#binomial-rvs"><i class="fa fa-check"></i><b>2.7.1</b> Binomial RVs</a></li>
<li class="chapter" data-level="2.7.2" data-path="probability.html"><a href="probability.html#geometric-rvs"><i class="fa fa-check"></i><b>2.7.2</b> Geometric RVs</a></li>
<li class="chapter" data-level="2.7.3" data-path="probability.html"><a href="probability.html#poisson-rvs"><i class="fa fa-check"></i><b>2.7.3</b> Poisson RVs</a></li>
<li class="chapter" data-level="2.7.4" data-path="probability.html"><a href="probability.html#negative-binomial-rvs"><i class="fa fa-check"></i><b>2.7.4</b> Negative Binomial RVs</a></li>
<li class="chapter" data-level="2.7.5" data-path="probability.html"><a href="probability.html#normal-rvs"><i class="fa fa-check"></i><b>2.7.5</b> Normal RVs</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="probability.html"><a href="probability.html#extra-stuff"><i class="fa fa-check"></i><b>2.8</b> Extra Stuff</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="probability.html"><a href="probability.html#sets-and-conditional-probability"><i class="fa fa-check"></i><b>2.8.1</b> Sets and Conditional Probability</a></li>
<li class="chapter" data-level="2.8.2" data-path="probability.html"><a href="probability.html#binomials-and-multinomials"><i class="fa fa-check"></i><b>2.8.2</b> Binomials and Multinomials</a></li>
<li class="chapter" data-level="2.8.3" data-path="probability.html"><a href="probability.html#expectation---baseball"><i class="fa fa-check"></i><b>2.8.3</b> Expectation - Baseball</a></li>
<li class="chapter" data-level="2.8.4" data-path="probability.html"><a href="probability.html#basketball-scenario"><i class="fa fa-check"></i><b>2.8.4</b> Basketball Scenario</a></li>
<li class="chapter" data-level="2.8.5" data-path="probability.html"><a href="probability.html#multiple-probability-distributions---basketball"><i class="fa fa-check"></i><b>2.8.5</b> Multiple Probability Distributions - Basketball</a></li>
<li class="chapter" data-level="2.8.6" data-path="probability.html"><a href="probability.html#law-of-total-probability---hockey"><i class="fa fa-check"></i><b>2.8.6</b> Law of Total Probability - Hockey</a></li>
<li class="chapter" data-level="2.8.7" data-path="probability.html"><a href="probability.html#law-of-total-probability---baseball"><i class="fa fa-check"></i><b>2.8.7</b> Law of Total Probability - Baseball</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="monte-carlo-simulation.html"><a href="monte-carlo-simulation.html"><i class="fa fa-check"></i><b>3</b> Monte Carlo Simulation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="monte-carlo-simulation.html"><a href="monte-carlo-simulation.html#basics"><i class="fa fa-check"></i><b>3.1</b> Basics</a></li>
<li class="chapter" data-level="3.2" data-path="monte-carlo-simulation.html"><a href="monte-carlo-simulation.html#estimating-probabilities"><i class="fa fa-check"></i><b>3.2</b> Estimating Probabilities</a></li>
<li class="chapter" data-level="3.3" data-path="monte-carlo-simulation.html"><a href="monte-carlo-simulation.html#a-few-reminderstips-for-simulation-and-a-basic-example"><i class="fa fa-check"></i><b>3.3</b> A few reminders/tips for simulation, and a basic example</a></li>
<li class="chapter" data-level="3.4" data-path="monte-carlo-simulation.html"><a href="monte-carlo-simulation.html#streak-simulation---basketball"><i class="fa fa-check"></i><b>3.4</b> Streak Simulation - Basketball</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#one-sample-and-two-sample-t-tests-and-confidence-intervals"><i class="fa fa-check"></i><b>4.1</b> One Sample and Two Sample t-tests and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>5</b> Correlation</a></li>
<li class="chapter" data-level="6" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>6</b> Linear Regression</a></li>
<li class="chapter" data-level="7" data-path="data-scraping.html"><a href="data-scraping.html"><i class="fa fa-check"></i><b>7</b> Data Scraping</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-scraping.html"><a href="data-scraping.html#wnba-scraping"><i class="fa fa-check"></i><b>7.1</b> wnba scraping</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html"><i class="fa fa-check"></i><b>8</b> Principal Component Analysis</a></li>
<li class="chapter" data-level="9" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>9</b> Clustering</a></li>
<li class="chapter" data-level="10" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>10</b> Classification</a></li>
<li class="chapter" data-level="11" data-path="decision-trees.html"><a href="decision-trees.html"><i class="fa fa-check"></i><b>11</b> Decision Trees</a>
<ul>
<li class="chapter" data-level="11.1" data-path="decision-trees.html"><a href="decision-trees.html#random-forests"><i class="fa fa-check"></i><b>11.1</b> Random Forests</a></li>
<li class="chapter" data-level="11.2" data-path="decision-trees.html"><a href="decision-trees.html#gradient-boosting"><i class="fa fa-check"></i><b>11.2</b> Gradient Boosting</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="non-parametric-statistics.html"><a href="non-parametric-statistics.html"><i class="fa fa-check"></i><b>12</b> Non-parametric Statistics</a></li>
<li class="chapter" data-level="13" data-path="baseball-1.html"><a href="baseball-1.html"><i class="fa fa-check"></i><b>13</b> Baseball</a></li>
<li class="chapter" data-level="14" data-path="football-1.html"><a href="football-1.html"><i class="fa fa-check"></i><b>14</b> Football</a></li>
<li class="chapter" data-level="15" data-path="basketball-1.html"><a href="basketball-1.html"><i class="fa fa-check"></i><b>15</b> Basketball</a></li>
<li class="chapter" data-level="16" data-path="soccer-1.html"><a href="soccer-1.html"><i class="fa fa-check"></i><b>16</b> Soccer</a></li>
<li class="chapter" data-level="17" data-path="hockey-1.html"><a href="hockey-1.html"><i class="fa fa-check"></i><b>17</b> Hockey</a></li>
<li class="chapter" data-level="18" data-path="volleyball-1.html"><a href="volleyball-1.html"><i class="fa fa-check"></i><b>18</b> Volleyball</a>
<ul>
<li class="chapter" data-level="18.1" data-path="volleyball-1.html"><a href="volleyball-1.html#resources"><i class="fa fa-check"></i><b>18.1</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="other-sports.html"><a href="other-sports.html"><i class="fa fa-check"></i><b>19</b> Other Sports</a></li>
<li class="chapter" data-level="20" data-path="text-solutions.html"><a href="text-solutions.html"><i class="fa fa-check"></i><b>20</b> Text solutions</a>
<ul>
<li class="chapter" data-level="20.1" data-path="text-solutions.html"><a href="text-solutions.html#chapter-1"><i class="fa fa-check"></i><b>20.1</b> Chapter 1</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="aarons-stuff.html"><a href="aarons-stuff.html"><i class="fa fa-check"></i><b>21</b> Aaron’s stuff</a>
<ul>
<li class="chapter" data-level="21.1" data-path="aarons-stuff.html"><a href="aarons-stuff.html#notes-for-chapter-2-probability"><i class="fa fa-check"></i><b>21.1</b> Notes for Chapter 2 (Probability)</a></li>
<li class="chapter" data-level="21.2" data-path="aarons-stuff.html"><a href="aarons-stuff.html#suggested-readings"><i class="fa fa-check"></i><b>21.2</b> Suggested Readings</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="aarons-stuff.html"><a href="aarons-stuff.html#moneyball"><i class="fa fa-check"></i><b>21.2.1</b> Moneyball</a></li>
<li class="chapter" data-level="21.2.2" data-path="aarons-stuff.html"><a href="aarons-stuff.html#future-value"><i class="fa fa-check"></i><b>21.2.2</b> Future Value</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="aarons-stuff.html"><a href="aarons-stuff.html#notes-for-chapter-4-simulation"><i class="fa fa-check"></i><b>21.3</b> Notes for Chapter 4 (Simulation)</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="aarons-stuff.html"><a href="aarons-stuff.html#baseball-simulation-example"><i class="fa fa-check"></i><b>21.3.1</b> Baseball Simulation Example</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Sports Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exploratory-data-analysis" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Exploratory Data Analysis<a href="exploratory-data-analysis.html#exploratory-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="getting-started-with-r" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Getting Started With R<a href="exploratory-data-analysis.html#getting-started-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="installing-r" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Installing R<a href="exploratory-data-analysis.html#installing-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this class, you will be using R Studio to complete statistical analyses on your computer.</p>
<p>To begin using R Studio, you will need to install “R” first and then install “R Studio” on your computer.</p>
<p><strong><em>Step 1: Download R</em></strong><br />
(a) Visit <a href="https://www.r-project.org/">https://www.r-project.org/</a><br />
(b) Click <strong>CRAN</strong> under <strong>Download</strong>
(c) Select any of the mirrors<br />
(d) Click the appropriate link for your type of system (Mac, Windows, Linux)<br />
(e) Download R on this next page.<br />
(For Windows, this will say <strong>install R for the first time</strong>. For Mac, this will be under <strong>Latest release</strong> and will be something like <strong>R-4.1.0.pkg</strong> – the numbers may differ depending on the most recent version)<br />
(f) Install R on your computer<br />
</p>
<p><strong><em>Step 2: Download R Studio</em></strong><br />
(a) Visit <a href="https://www.rstudio.com/products/rstudio/download/#download">https://www.rstudio.com/products/rstudio/download/#download</a><br />
(b) Click to download<br />
(c) Install R Studio on your computer<br />
</p>
<p><strong><em>Step 3: Verify R Studio is working</em></strong><br />
(a) Open R Studio<br />
(b) Let’s enter a small dataset and calculate the average to make sure everything is working correctly.<br />
(c) In the console, type in the following dataset of Sammy Sosa’s season home run totals from 1998–2002:<br />
</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="exploratory-data-analysis.html#cb1-1" aria-hidden="true" tabindex="-1"></a>sosa.HR <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">66</span>, <span class="dv">63</span>, <span class="dv">50</span>, <span class="dv">64</span>, <span class="dv">49</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: lower-alpha">
<li>In the console, calculate the average season home run total for Sammy Sosa between 1998–2002:<br />
</li>
</ol>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="exploratory-data-analysis.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sosa.HR)</span></code></pre></div>
<pre><code>## [1] 58.4</code></pre>
<p>(e) Did you find Slammin’ Sammy’s average home run total from 1998–2002 was 58.4? If so, you should be set up correctly!</p>
</div>
<div id="some-r-basics" class="section level3 hasAnchor" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Some R Basics<a href="exploratory-data-analysis.html#some-r-basics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the following examples, let’s consider Peyton Manning’s career with the Denver Broncos. In his four seasons with the Broncos, Manning’s passing yard totals were: 4659, 5477, 4727, 2249. Let’s enter this data into R. To enter a vector of data, use the <strong>c()</strong> function.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="exploratory-data-analysis.html#cb4-1" aria-hidden="true" tabindex="-1"></a>peyton <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4659</span>, <span class="dv">5477</span>, <span class="dv">4727</span>, <span class="dv">2249</span>)</span></code></pre></div>
<p>To look at the data you just put in the variable <em>peyton</em>, type <em>peyton</em> into the console and press enter.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="exploratory-data-analysis.html#cb5-1" aria-hidden="true" tabindex="-1"></a>peyton</span></code></pre></div>
<pre><code>## [1] 4659 5477 4727 2249</code></pre>
<p>Some basic function for calculating summary statistics include <strong>summary</strong>, <strong>mean()</strong>, <strong>median()</strong>, <strong>var()</strong>, and <strong>sd()</strong>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="exploratory-data-analysis.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(peyton)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2249    4056    4693    4278    4914    5477</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="exploratory-data-analysis.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(peyton)</span></code></pre></div>
<pre><code>## [1] 4278</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="exploratory-data-analysis.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(peyton)</span></code></pre></div>
<pre><code>## [1] 1402.522</code></pre>
<p>R allows you to install additional packages (collections of functions) that aren’t offered in the base version of R. To install a package, use <strong>install.packages(<name_of_package>)</strong> and to load a package, use <strong>library(<name_of_package>)</strong>.</p>
<p>One package that we will use frequently is <strong>tidyverse</strong>. This package includes several other packages and functions such as <strong>ggplot</strong> (plotting function), <strong>dplyr</strong> (data manipulation package), and <strong>stringr</strong> (string manipulation package).</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="exploratory-data-analysis.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</span>
<span id="cb13-2"><a href="exploratory-data-analysis.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tidyverse&quot;</span>)</span></code></pre></div>
<p>You will also need to know how to load datasets from files. For this class, we will typically provide data files is .csv format.</p>
<p>Here is how to load a file:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="exploratory-data-analysis.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load readr package and load example dataset</span></span>
<span id="cb14-2"><a href="exploratory-data-analysis.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb14-3"><a href="exploratory-data-analysis.html#cb14-3" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/NFL_2021_Team_Passing.csv&quot;</span>)</span>
<span id="cb14-4"><a href="exploratory-data-analysis.html#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="exploratory-data-analysis.html#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># we can look at the header (first few entries) using &#39;head()&#39;</span></span>
<span id="cb14-6"><a href="exploratory-data-analysis.html#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(NFL_2021_Team_Passing)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 25
##      Rk Tm             G   Cmp   Att `Cmp%`   Yds    TD `TD%`   Int `Int%`   Lng
##   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1     1 Tampa Bay…    17   492   731   67.3  5229    43   5.9    12    1.6    62
## 2     2 Los Angel…    17   443   674   65.7  4800    38   5.6    15    2.2    72
## 3     3 Dallas Co…    17   444   647   68.6  4800    40   6.2    11    1.7    73
## 4     4 Kansas Ci…    17   448   675   66.4  4791    37   5.5    13    1.9    75
## 5     5 Los Angel…    17   406   607   66.9  4642    41   6.8    18    3      79
## 6     6 Las Vegas…    17   429   628   68.3  4567    23   3.7    14    2.2    61
## # … with 13 more variables: `Y/A` &lt;dbl&gt;, `AY/A` &lt;dbl&gt;, `Y/C` &lt;dbl&gt;,
## #   `Y/G` &lt;dbl&gt;, Rate &lt;dbl&gt;, Sk &lt;dbl&gt;, SKYds &lt;dbl&gt;, `Sk%` &lt;dbl&gt;, `NY/A` &lt;dbl&gt;,
## #   `ANY/A` &lt;dbl&gt;, `4QC` &lt;dbl&gt;, GWD &lt;dbl&gt;, EXP &lt;dbl&gt;</code></pre>
<div style="page-break-after: always;"></div>
</div>
</div>
<div id="descriptive-statistics" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Descriptive Statistics<a href="exploratory-data-analysis.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="definitions" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Definitions<a href="exploratory-data-analysis.html#definitions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="definition">
<p><span id="def:unlabeled-div-1" class="definition"><strong>Definition 1.1  </strong></span>A <strong><em>population</em></strong> is a well-defined complete collection of objects.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-2" class="definition"><strong>Definition 1.2  </strong></span>A <strong><em>sample</em></strong> is a subset of the population.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-3" class="example"><strong>Example 1.1  </strong></span>Suppose we are interested in studying Peyton’s Manning’s season passing yards totals. How could you define the population and what is one possible sample?</p>
</div>
<p><br />
<br />
<br />
<br />
<br />
</p>
<div class="definition">
<p><span id="def:unlabeled-div-4" class="definition"><strong>Definition 1.3  </strong></span><strong><em>Quantitative data</em></strong> is numeric data or numbers. It can be broken into two further categories: discrete and continuous data.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-5" class="definition"><strong>Definition 1.4  </strong></span><strong><em>Discrete data</em></strong> is quantitative data with a finite or countably infinite number of values.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-6" class="definition"><strong>Definition 1.5  </strong></span><strong><em>Continuous data</em></strong> is quantitative data with an uncountably infinite number of values or data taken from an interval.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-7" class="example"><strong>Example 1.2  </strong></span>What are possible discrete and continuous data associated with Peyton Manning?</p>
</div>
<p><br />
<br />
<br />
<br />
<br />
</p>
<div class="definition">
<p><span id="def:unlabeled-div-8" class="definition"><strong>Definition 1.6  </strong></span><strong><em>Qualitative data</em></strong> refers to names, categories, or descriptions. It can also be broken down into
two further categories, nominal data and ordinal data.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-9" class="definition"><strong>Definition 1.7  </strong></span><strong><em>Nominal data</em></strong> is qualitative data with no natural ordering.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-10" class="definition"><strong>Definition 1.8  </strong></span><strong><em>Ordinal data</em></strong> is qualitative data with a natural ordering.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-11" class="example"><strong>Example 1.3  </strong></span>What are possible nominal and ordinal data associated with Peyton Manning?</p>
</div>
<p><br />
<br />
<br />
<br />
<br />
</p>
<hr />
</div>
<div id="descriptive-statistics-1" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Descriptive Statistics<a href="exploratory-data-analysis.html#descriptive-statistics-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>While we will learn about some descriptive statistics that are unique to specific sports, there are some descriptive statistics that are frequently used in many applications.</p>
<div id="descriptive-statistics-for-quantitative-data" class="section level4 hasAnchor" number="1.2.2.1">
<h4><span class="header-section-number">1.2.2.1</span> Descriptive Statistics for Quantitative Data<a href="exploratory-data-analysis.html#descriptive-statistics-for-quantitative-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are different descriptive statistics depending on the type of data you are analyzing. We will begin by looking at descriptive statistics for quantitative data.</p>
<p>To begin, let <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> represent a numerical dataset with a sample of size <span class="math inline">\(n\)</span>, where <span class="math inline">\(x_i\)</span> is the <span class="math inline">\(i^\text{th}\)</span> value in the dataset.</p>
<div class="definition">
<p><span id="def:unlabeled-div-12" class="definition"><strong>Definition 1.9  </strong></span>The <strong><em>sum</em></strong> of the data values is given by: <span class="math inline">\(\sum_{i=1}^n x_i = x_1 + x_2 + \ldots + x_n\)</span></p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-13" class="definition"><strong>Definition 1.10  </strong></span>The <strong><em>sample mean</em></strong> (or sample average), <span class="math inline">\(\bar{x}\)</span>, of the numerical dataset is given by <span class="math inline">\(\bar{x} = \frac{1}{n} \sum_{i=1}^n x_i\)</span></p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-14" class="definition"><strong>Definition 1.11  </strong></span>The <strong><em>population mean</em></strong> (or population average), <span class="math inline">\(\mu\)</span>, is the mean value for the entire population.</p>
</div>
<p>The mean can be thought of as a measure of center or more generally, a measure of location.</p>
<div class="example">
<p><span id="exm:unlabeled-div-15" class="example"><strong>Example 1.4  </strong></span>Recall that Peyton Manning’s season passing yards total while with the Broncos were: 4659, 5477, 4727, 2249. Calculate the sample mean of these values.</p>
</div>
<p><br />
<br />
<br />
<br />
<br />
</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="exploratory-data-analysis.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the sample of Peyton Manning&#39;s passing yards season totals with</span></span>
<span id="cb16-2"><a href="exploratory-data-analysis.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Colts</span></span>
<span id="cb16-3"><a href="exploratory-data-analysis.html#cb16-3" aria-hidden="true" tabindex="-1"></a>peyton.broncos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4659</span>, <span class="dv">5477</span>, <span class="dv">4727</span>, <span class="dv">2249</span>)</span>
<span id="cb16-4"><a href="exploratory-data-analysis.html#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(peyton.broncos)</span></code></pre></div>
<pre><code>## [1] 4278</code></pre>
<p>In sports statistics, we often have to choose between using a descriptive statistic that summarizes a quantity versus a descriptive statistic that summarizes a rate. For instance, in basketball, we can compare two players based on how many points they score in a game (total quantity) or we can compare two players based on how many points per minute played (rate statistic). Many applications in sports analytics focus more on rate statistics rather than quantity statistics. Why?</p>
<p>We can measure the spread or variability of a dataset using <em>variance</em> and <em>standard devatiation</em>.</p>
<div class="definition">
<p><span id="def:unlabeled-div-16" class="definition"><strong>Definition 1.12  </strong></span>The <strong><em>sample variance</em></strong>, <span class="math inline">\(s^2\)</span>, of the numerical dataset is a measure of spread and is given by <span class="math inline">\(s^2 = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2\)</span></p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-17" class="definition"><strong>Definition 1.13  </strong></span>The <strong><em>sample standard deviation</em></strong>, <span class="math inline">\(s\)</span>, of the numerical dataset is a measure of spread and is given by <span class="math inline">\(s = \sqrt{s^2} = \sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}\)</span></p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-18" class="definition"><strong>Definition 1.14  </strong></span>The <strong><em>population variance</em></strong>, <span class="math inline">\(\sigma^2\)</span>, is the variance for an entire population.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-19" class="definition"><strong>Definition 1.15  </strong></span>The <strong><em>population standard deviation</em></strong>, <span class="math inline">\(\sigma\)</span>, is the standard deviation for an entire population.</p>
</div>
<p>We often prefer to work with standard deviations as a measure of spread as opposed to variance because standard deviations are given in our original units.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="exploratory-data-analysis.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the variance and standard deviation of Peyton Manning&#39;s passing</span></span>
<span id="cb18-2"><a href="exploratory-data-analysis.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># yards season totals with Broncos</span></span>
<span id="cb18-3"><a href="exploratory-data-analysis.html#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(peyton.broncos)  <span class="co"># units: yards^2</span></span></code></pre></div>
<pre><code>## [1] 1967068</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="exploratory-data-analysis.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(peyton.broncos)  <span class="co"># units: yards</span></span></code></pre></div>
<pre><code>## [1] 1402.522</code></pre>
<div class="definition">
<p><span id="def:unlabeled-div-20" class="definition"><strong>Definition 1.16  </strong></span>The <strong>sample median</strong>, <span class="math inline">\(\tilde{x}\)</span>, of a numerical dataset is the middle value when the data are ordered from smallest to largest. In other words, let <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> be the (unordered) dataset and let <span class="math inline">\(x_{(1)},x_{(2)}, \ldots, x_{(n)}\)</span> be the same dataset but ordered from smallest to largest. If <span class="math inline">\(n\)</span> is odd, then <span class="math inline">\(\tilde{x} = x_{(n+1)/2}\)</span> and if <span class="math inline">\(n\)</span> is even, then <span class="math inline">\(\tilde{x} = \frac{1}{2} \cdot \left[x_{\left(\frac{n}{2}\right)} + x_{\left(\frac{n+1}{2}\right)}\right]\)</span>.</p>
</div>
<div class="example">
<p><span id="exm:unlabeled-div-21" class="example"><strong>Example 1.5  </strong></span>Calculate the sample median of Peyton Manning’s season passing yards total while with the Colts (3739, 4135, 4413, 4131, 4200, 4267, 4557, 3747, 4397, 4040, 4002, 4500, 4700).</p>
</div>
<p><br />
<br />
<br />
<br />
<br />
</p>
<p>Like sample mean, sample median is a measure of center. It gives you an idea of where the ``middle” of your dataset is.</p>
<p>We can calculate sample mean and sample median in R as follows:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="exploratory-data-analysis.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the median of Peyton Manning&#39;s passing yards season totals with</span></span>
<span id="cb22-2"><a href="exploratory-data-analysis.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Broncos and Colts</span></span>
<span id="cb22-3"><a href="exploratory-data-analysis.html#cb22-3" aria-hidden="true" tabindex="-1"></a>peyton.colts <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3739</span>, <span class="dv">4135</span>, <span class="dv">4413</span>, <span class="dv">4131</span>, <span class="dv">4200</span>, <span class="dv">4267</span>, <span class="dv">4557</span>, <span class="dv">3747</span>, <span class="dv">4397</span>, <span class="dv">4040</span>, <span class="dv">4002</span>,</span>
<span id="cb22-4"><a href="exploratory-data-analysis.html#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">4500</span>, <span class="dv">4700</span>)</span>
<span id="cb22-5"><a href="exploratory-data-analysis.html#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(peyton.broncos)</span></code></pre></div>
<pre><code>## [1] 4693</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="exploratory-data-analysis.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(peyton.colts)</span></code></pre></div>
<pre><code>## [1] 4200</code></pre>
<div class="definition">
<p><span id="def:unlabeled-div-22" class="definition"><strong>Definition 1.17  </strong></span>A <strong><em>percentile</em></strong> is a measure of relative standing. The <span class="math inline">\(p^\text{th}\)</span> percentile is the number where at least
p% of the data values are less than or equal to this number.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-23" class="definition"><strong>Definition 1.18  </strong></span>A <strong><em>quantile</em></strong> is a measure of relative standing and are the cut points for breaking a distribution of values into equal sized bins.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-24" class="definition"><strong>Definition 1.19  </strong></span>A <strong><em>quartile</em></strong> is a measure of relative standing and are the cut points for breaking a distribution of values into four equal parts.</p>
</div>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="exploratory-data-analysis.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the 10th and 90th percentile of Peyton Manning&#39;s passing yards</span></span>
<span id="cb26-2"><a href="exploratory-data-analysis.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># season totals with Colts</span></span>
<span id="cb26-3"><a href="exploratory-data-analysis.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(peyton.colts, <span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>##  10% 
## 3798</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="exploratory-data-analysis.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(peyton.colts, <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>##    90% 
## 4545.6</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="exploratory-data-analysis.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(peyton.colts, <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>))</span></code></pre></div>
<pre><code>##    10%    90% 
## 3798.0 4545.6</code></pre>
<p><strong>Special percentiles:</strong><br />
1. 25th percentile = 1st quartile = <span class="math inline">\(Q_1\)</span><br />
2. 50th percentile = 2nd quartile = <span class="math inline">\(Q_2\)</span> = <span class="math inline">\(\tilde{x}\)</span><br />
3. 75th percentile = 3rd quartile = <span class="math inline">\(Q_3\)</span><br />
</p>
<div class="definition">
<p><span id="def:unlabeled-div-25" class="definition"><strong>Definition 1.20  </strong></span><strong><em>Range</em></strong> is a measure of spread, measures the full width of a dataset, and is given by: <span class="math inline">\(Range = Max - Min\)</span>.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-26" class="definition"><strong>Definition 1.21  </strong></span><strong><em>Interquartile range</em></strong> is a measure of spread, measures the width of the middle 50% of a dataset, and is given by: <span class="math inline">\(IQR = Q_3 - Q_1\)</span>.</p>
</div>
<div class="definition">
<p><span id="def:unlabeled-div-27" class="definition"><strong>Definition 1.22  </strong></span>A <strong><em>five number summary</em></strong> describes the center, spread, and edges of a dataset and is given by: <span class="math inline">\((Min,Q_1,Q_2,Q_3,max)\)</span>.</p>
</div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="exploratory-data-analysis.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(peyton.colts)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    3739    4040    4200    4218    4413    4700</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="exploratory-data-analysis.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(peyton.colts, <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
## 3739 4040 4200 4413 4700</code></pre>
</div>
<div id="descriptive-statistics-for-qualitative-data" class="section level4 hasAnchor" number="1.2.2.2">
<h4><span class="header-section-number">1.2.2.2</span> Descriptive Statistics for Qualitative Data<a href="exploratory-data-analysis.html#descriptive-statistics-for-qualitative-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In sports statistics, we also encounter qualitative (categorical) data which is names or labels which has its own descriptive statistics.</p>
<p>To begin, let <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> represent a categorical dataset with a sample of size <span class="math inline">\(n\)</span>, where <span class="math inline">\(x_i\)</span> is the <span class="math inline">\(i^\text{th}\)</span> value in the dataset.</p>
<div class="definition">
<p><span id="def:unlabeled-div-28" class="definition"><strong>Definition 1.23  </strong></span>The <strong><em>proportion</em></strong> of sampled data that fall into a category is given by: <span class="math inline">\(p = \frac{\#\text{ in category}}{\#\text{ total}}\)</span></p>
</div>
<p>’’Proportion” and “Probability” are often used interchangeably. Both have a minimum value of 0 and a maximum value of 1.</p>
<div class="definition">
<p><span id="def:unlabeled-div-29" class="definition"><strong>Definition 1.24  </strong></span>The <strong><em>percentage</em></strong> of sampled data that fall into a category is given by: <span class="math inline">\(P\% = 100 \cdot p = 100 \cdot \frac{\#\text{ in category}}{\#\text{ total}}\)</span></p>
</div>
<p>Percentages in this context can have a minimum value of 0% and a maximum value of 100%.</p>
<div class="example">
<p><span id="exm:unlabeled-div-30" class="example"><strong>Example 1.6  </strong></span>In 2014, Peyton Manning started as quarterback for the Denver Broncos. The result of the Broncos’ 16-game season was:<br />
Win, Win, Loss, Win, Win, Win, Win, Loss, Win, Loss, Win, Win, Win, Win, Loss, Win</p>
<p>Calculate the proportion and percentage of Broncos’ winning games in 2014.</p>
</div>
<p><br />
<br />
<br />
<br />
<br />
</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="exploratory-data-analysis.html#cb36-1" aria-hidden="true" tabindex="-1"></a>broncos2014 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Loss&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Loss&quot;</span>, <span class="st">&quot;Win&quot;</span>,</span>
<span id="cb36-2"><a href="exploratory-data-analysis.html#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Loss&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Win&quot;</span>, <span class="st">&quot;Loss&quot;</span>, <span class="st">&quot;Win&quot;</span>)</span>
<span id="cb36-3"><a href="exploratory-data-analysis.html#cb36-3" aria-hidden="true" tabindex="-1"></a>broncos.prop <span class="ot">&lt;-</span> <span class="fu">sum</span>(broncos2014 <span class="sc">==</span> <span class="st">&quot;Win&quot;</span>)<span class="sc">/</span><span class="fu">length</span>(broncos2014)</span>
<span id="cb36-4"><a href="exploratory-data-analysis.html#cb36-4" aria-hidden="true" tabindex="-1"></a>broncos.prop</span></code></pre></div>
<pre><code>## [1] 0.75</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="exploratory-data-analysis.html#cb38-1" aria-hidden="true" tabindex="-1"></a>broncos.perc <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> broncos.prop</span>
<span id="cb38-2"><a href="exploratory-data-analysis.html#cb38-2" aria-hidden="true" tabindex="-1"></a>broncos.perc</span></code></pre></div>
<pre><code>## [1] 75</code></pre>
<p>We can also build a frequency table that summarizes the categories and their occurrences using <strong>table()</strong> in R. Note that <strong>table()</strong> works for quantitative and qualitative data.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="exploratory-data-analysis.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(broncos2014)</span></code></pre></div>
<pre><code>## broncos2014
## Loss  Win 
##    4   12</code></pre>
<div style="page-break-after: always;"></div>
</div>
</div>
</div>
<div id="visualizations" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Visualizations<a href="exploratory-data-analysis.html#visualizations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Conveying information visually is also an important part in providing a description of a dataset.</p>
<p>R provides some basic plotting functions such as <strong>plot</strong>, <strong>hist</strong>, and <strong>barplot</strong>. These plotting functions are simple and not always very clean looking.</p>
<p>In this class, we will use analogous plotting functions in <strong>ggplot2</strong> that are much improved plotting functions.</p>
<p>If you have already installed the <strong>tidyverse</strong> package, it should have also installed the <strong>ggplot2</strong> package.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="exploratory-data-analysis.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You have likely already installed the tidyverse package but if not, use the</span></span>
<span id="cb42-2"><a href="exploratory-data-analysis.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># following command without the &#39;#&#39; install.packages(&#39;tidyverse&#39;)</span></span>
<span id="cb42-3"><a href="exploratory-data-analysis.html#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="exploratory-data-analysis.html#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the tidyverse package (which includes ggplot2)</span></span>
<span id="cb42-5"><a href="exploratory-data-analysis.html#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.3.6     ✔ dplyr   1.0.9
## ✔ tibble  3.1.7     ✔ stringr 1.4.0
## ✔ tidyr   1.2.0     ✔ forcats 0.5.1
## ✔ purrr   0.3.4</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<p>Let’s load the file ``NFL_2021_Team_Passing.csv” which contains <a href="https://www.pro-football-reference.com/years/2021/index.htm#passing">NFL Team Passing Statistics, 2021</a></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="exploratory-data-analysis.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb46-2"><a href="exploratory-data-analysis.html#cb46-2" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/NFL_2021_Team_Passing.csv&quot;</span>)</span></code></pre></div>
<p>Histograms are one of the most common and basic ways to visualize a dataset’s distribution of values. To make a histogram, you will use <strong>ggplot</strong> and <strong>geom_histogram</strong>.</p>
<div class="example">
<p><span id="exm:unlabeled-div-31" class="example"><strong>Example 1.7  </strong></span>Create a histogram of the NFL Team Passing Yards in 2021.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="exploratory-data-analysis.html#cb47-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="exploratory-data-analysis.html#cb47-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="series_files/figure-html/hist-1.png" width="672" /></p>
<p>Notice how <strong>%&gt;%</strong> is used to <strong>pipe</strong> the dataset into ggplot. This is using the pipe function from the <strong>dplyr</strong> package.</p>
<p>By default, <strong>geom_histogram</strong> uses 30 bins but this is customizable. Let’s make the bins have a width of 200.</p>
<p>All good visualizations have good labels. Let’s improve the axis labels and give the figure a title.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="exploratory-data-analysis.html#cb48-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="exploratory-data-analysis.html#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">200</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb48-3"><a href="exploratory-data-analysis.html#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/hist2-1.png" width="672" /></p>
<p>We also have numerous options to change the appearance of plots when using <strong>ggplot</strong>. Let’s change the bins color to <em>blue</em> and change the bin borders to <em>white</em>.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="exploratory-data-analysis.html#cb49-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="exploratory-data-analysis.html#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">binwidth =</span> <span class="dv">200</span>) <span class="sc">+</span></span>
<span id="cb49-3"><a href="exploratory-data-analysis.html#cb49-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/hist3-1.png" width="672" /></p>
</div>
<p>We can also create bar plots using ggplot using the <strong>geom_bar</strong> function.</p>
<div class="example">
<p><span id="exm:unlabeled-div-32" class="example"><strong>Example 1.8  </strong></span>Create a bar plot with teams on the horizontal axis and passing touchdowns on the vertical axis.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="exploratory-data-analysis.html#cb50-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="exploratory-data-analysis.html#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Tm, <span class="at">y =</span> Yds)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/bar-1.png" width="672" /></p>
<p>The team labels are a complete mess. Let’s fix this and make some adjustments to the axis labels and figure title.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="exploratory-data-analysis.html#cb51-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="exploratory-data-analysis.html#cb51-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Tm, <span class="at">y =</span> Yds)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb51-3"><a href="exploratory-data-analysis.html#cb51-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>,</span>
<span id="cb51-4"><a href="exploratory-data-analysis.html#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="series_files/figure-html/bar2-1.png" width="672" /></p>
<p>We can flip this graph if we like as well. Note that when we flip the graph, our labels get in reverse ordering, so this can be fixed using <strong>fct_rev()</strong> which is part of the <strong>forcats</strong> package.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="exploratory-data-analysis.html#cb52-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="exploratory-data-analysis.html#cb52-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(Tm), <span class="at">y =</span> Yds)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb52-3"><a href="exploratory-data-analysis.html#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>) <span class="sc">+</span> <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="series_files/figure-html/bar3-1.png" width="672" /></p>
</div>
<p>Another common and useful visualization is a scatterplot which shows the relationship between two numeric variable. In ggplot, you use <strong>geom_point()</strong>.</p>
<div class="example">
<p><span id="exm:unlabeled-div-33" class="example"><strong>Example 1.9  </strong></span>Create a scatterplot of Team Passing Yards and Team Passing Touchdowns from the NFL 2021 dataset.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="exploratory-data-analysis.html#cb53-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="exploratory-data-analysis.html#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds, <span class="at">y =</span> TD, <span class="at">label =</span> Tm)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb53-3"><a href="exploratory-data-analysis.html#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/scatter1-1.png" width="672" /></p>
<p>We may want to include team labels on this plot, however, it can get messy very quickly with a lot of points.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="exploratory-data-analysis.html#cb54-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="exploratory-data-analysis.html#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds, <span class="at">y =</span> TD, <span class="at">label =</span> Tm)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb54-3"><a href="exploratory-data-analysis.html#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text</span>()</span></code></pre></div>
<p><img src="series_files/figure-html/scatter2-1.png" width="672" /></p>
<p>Many sports leagues have around 30 teams, so a clean scatterplot with labels can be tricky to make. Here are some options below.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="exploratory-data-analysis.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install ggrepel package</span></span>
<span id="cb55-2"><a href="exploratory-data-analysis.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb55-3"><a href="exploratory-data-analysis.html#cb55-3" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="exploratory-data-analysis.html#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds, <span class="at">y =</span> TD, <span class="at">label =</span> Tm)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb55-5"><a href="exploratory-data-analysis.html#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text_repel</span>()</span></code></pre></div>
<pre><code>## Warning: ggrepel: 6 unlabeled data points (too many overlaps). Consider
## increasing max.overlaps</code></pre>
<p><img src="series_files/figure-html/scatter3-1.png" width="672" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="exploratory-data-analysis.html#cb57-1" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing<span class="sc">$</span>Abbr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;TB&quot;</span>, <span class="st">&quot;LAC&quot;</span>, <span class="st">&quot;DAL&quot;</span>, <span class="st">&quot;KC&quot;</span>, <span class="st">&quot;LAR&quot;</span>, <span class="st">&quot;LV&quot;</span>, <span class="st">&quot;CIN&quot;</span>, <span class="st">&quot;GB&quot;</span>,</span>
<span id="cb57-2"><a href="exploratory-data-analysis.html#cb57-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;BUF&quot;</span>, <span class="st">&quot;AZ&quot;</span>, <span class="st">&quot;MN&quot;</span>, <span class="st">&quot;SF&quot;</span>, <span class="st">&quot;BAL&quot;</span>, <span class="st">&quot;NE&quot;</span>, <span class="st">&quot;PIT&quot;</span>, <span class="st">&quot;ATL&quot;</span>, <span class="st">&quot;MIA&quot;</span>, <span class="st">&quot;DET&quot;</span>, <span class="st">&quot;DEN&quot;</span>, <span class="st">&quot;NYJ&quot;</span>,</span>
<span id="cb57-3"><a href="exploratory-data-analysis.html#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;WAS&quot;</span>, <span class="st">&quot;JAC&quot;</span>, <span class="st">&quot;SEA&quot;</span>, <span class="st">&quot;TEN&quot;</span>, <span class="st">&quot;PHI&quot;</span>, <span class="st">&quot;IND&quot;</span>, <span class="st">&quot;CLE&quot;</span>, <span class="st">&quot;HOU&quot;</span>, <span class="st">&quot;CAR&quot;</span>, <span class="st">&quot;CHI&quot;</span>, <span class="st">&quot;NYG&quot;</span>,</span>
<span id="cb57-4"><a href="exploratory-data-analysis.html#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;NO&quot;</span>)</span>
<span id="cb57-5"><a href="exploratory-data-analysis.html#cb57-5" aria-hidden="true" tabindex="-1"></a>NFL_2021_Team_Passing <span class="sc">%&gt;%</span></span>
<span id="cb57-6"><a href="exploratory-data-analysis.html#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Yds, <span class="at">y =</span> TD, <span class="at">label =</span> Abbr)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Team Passing Yards&quot;</span>,</span>
<span id="cb57-7"><a href="exploratory-data-analysis.html#cb57-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Team Passing Touchdowns&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NFL Team Passing Yards, 2021&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text_repel</span>(<span class="at">box.padding =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/scatter4-1.png" width="672" /></p>
</div>
<div style="page-break-after: always;"></div>
</div>
<div id="baseball" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Baseball<a href="exploratory-data-analysis.html#baseball" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div style="page-break-after: always;"></div>
</div>
<div id="football" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Football<a href="exploratory-data-analysis.html#football" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div style="page-break-after: always;"></div>
</div>
<div id="basketball" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Basketball<a href="exploratory-data-analysis.html#basketball" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://www.youtube.com/watch?v=wYjp2zoqQrs">Link to YouTube video describing basketball rules</a></p>
<div id="basic-basketball-statistics" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Basic Basketball Statistics<a href="exploratory-data-analysis.html#basic-basketball-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Field Goal (FG)</strong>: A made shot from either 2- or 3-point range. Free throws, worth 1 point, are not considered field goals. Field goal statistics often include attempts, makes, and percentage.</p></li>
<li><p><strong>Free Throw (FT)</strong>: After certain fouls, the clock stops and a player shoots an uncontested shot from the foul line. These free throws are worth 1 point each; like with field goals, FT statistics often include attempts, makes, and percentage.</p></li>
<li><p><strong>Assists (AST)</strong>: A player is credited with an assist if they pass the ball to a teammate and the teammate scores a field goal after zero or one dribbles. No more than one assist can be recorded per field goal.</p></li>
<li><p><strong>Turnover (TO)</strong>: A player or team can be charged with a turnover for an action or violation that ends their offensive possession before being able to attempt a field goal. For a player (especially a guard), TOs can be compared to assists using Assist:Turnover ratio.</p></li>
<li><p><strong>Rebound (REB)</strong>: The first player to gain control of the ball following a missed field goal is credited with a rebound. If the player is on the same team as the field goal shooter, it is an offensive rebound; otherwise, a defensive rebound.</p></li>
<li><p><strong>Points per Possession (PPP)</strong>: Divides a team’s points by number of possessions to account for a team’s pace.</p></li>
</ul>
</div>
<div id="advanced-basketball-statistics" class="section level3 hasAnchor" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Advanced Basketball Statistics<a href="exploratory-data-analysis.html#advanced-basketball-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>True Shooting Percentage (TS%)</strong>: Unlike traditional shooting percentage, this statistic considers both field goals and free throws. It also gives more weight to shots that are worth more points.</p></li>
<li><p><strong>Win Shares</strong>: Win shares give each player points for actions that contribute to a team’s success. Win shares take into account a variety of offensive and defensive statistics, but can be calculated using different methods on different platforms.</p></li>
<li><p><strong>Value Over Replacement Player (VORP)</strong>: This is basketball’s response to baseball’s WAR. VORP is a rate statistic that estimates a player’s offensive output as compared to an “average” player.</p></li>
<li><p><strong>Player Efficiency Rating (PER)</strong>: According to its creator John Hollinger,
“The PER sums up all a player’s positive accomplishments, subtracts the negative accomplishments, and returns a per-minute rating of a player’s performance.” This statistic rewards great offensive performance more than great defensive plays.</p></li>
</ul>
<p><em>References: <a href="https://www.basketball-reference.com/about/per.html" class="uri">https://www.basketball-reference.com/about/per.html</a>, <a href="https://www.basketball-reference.com/about/ws.html" class="uri">https://www.basketball-reference.com/about/ws.html</a>, <a href="https://www.basketball-reference.com/about/glossary.html" class="uri">https://www.basketball-reference.com/about/glossary.html</a></em></p>
</div>
<div id="four-factors" class="section level3 hasAnchor" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Four Factors<a href="exploratory-data-analysis.html#four-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Tibbles are a type of data frame supported by the <code>tidyverse</code> package. The following tibble contains data from a Mountain West tournament game played between the CSU and Wyoming women’s basketball teams during the 2021-2022 season, which CSU won 51-38. <a href="https://csurams.com/sports/womens-basketball/stats/2021-22/wyoming/boxscore/16095">(Here’s the link to the box score on the CSU athletics website.)</a></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="exploratory-data-analysis.html#cb58-1" aria-hidden="true" tabindex="-1"></a>basketball_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">team =</span> <span class="fu">c</span>(<span class="st">&quot;CSU&quot;</span>, <span class="st">&quot;WYO&quot;</span>), <span class="at">FG =</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">15</span>), <span class="at">FGA =</span> <span class="fu">c</span>(<span class="dv">48</span>, <span class="dv">60</span>),</span>
<span id="cb58-2"><a href="exploratory-data-analysis.html#cb58-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">THREEP =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>), <span class="at">FT =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">4</span>), <span class="at">FTA =</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">4</span>), <span class="at">ORB =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">14</span>), <span class="at">DRB =</span> <span class="fu">c</span>(<span class="dv">31</span>,</span>
<span id="cb58-3"><a href="exploratory-data-analysis.html#cb58-3" aria-hidden="true" tabindex="-1"></a>        <span class="dv">30</span>), <span class="at">TOV =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">12</span>))</span>
<span id="cb58-4"><a href="exploratory-data-analysis.html#cb58-4" aria-hidden="true" tabindex="-1"></a>basketball_data</span></code></pre></div>
<pre><code>## # A tibble: 2 × 9
##   team     FG   FGA THREEP    FT   FTA   ORB   DRB   TOV
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 CSU      14    48      5    10    14     2    31     5
## 2 WYO      15    60      4     4     4    14    30    12</code></pre>
<p>This tibble contains all the data needed to calculate the <em>Four Factors</em>. The Four Factors of a basketball game are statistics formulated by Dean Oliver, former Director of Quantitative Analysis for the Denver Nuggets (among other roles). These statistics are also promoted by sports data platforms like Hudl.com.</p>
<p>The Four Factors each have offensive and defensive versions; for this example, we’ll focus on the offensive perspective.</p>
<p>The first is <strong>Effective Field Goal Percentage</strong>, commonly abbreviated eFG%. The formula is as follows:</p>
<p><span class="math inline">\(eFG\% = \frac{FG\ +\ 0.5(3P)}{FGA}\)</span></p>
<p>Secondly, <strong>Turnover Percentage</strong> (TOV%) is calculated as:</p>
<p><span class="math inline">\(TOV\% = \frac{TOV}{FGA\ +\ 0.44(FTA)\ +\ TOV}\)</span></p>
<p>Next, <strong>Rebounding Percentage</strong> (ORB%) is computed as:</p>
<p><span class="math inline">\(ORB\% = \frac{ORB}{ORB\ +\ Opponent\ DRB}\)</span></p>
<p>Finally, the <strong>Free Throw Factor</strong> is found using:</p>
<p><span class="math inline">\(FT\ factor = \frac{FT}{FGA}\)</span></p>
<p>Note: You do not have to know these formulas for the test. They are just used for this example.</p>
<p>Let’s calculate the values of eFG%, TOV%, ORB%, and Free Throw Factor for both CSU and Wyoming and add them as new columns in the tibble using the <code>add_column</code> function.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="exploratory-data-analysis.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(basketball_data)</span>
<span id="cb60-2"><a href="exploratory-data-analysis.html#cb60-2" aria-hidden="true" tabindex="-1"></a>eFG <span class="ot">&lt;-</span> <span class="fu">round</span>((FG <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> THREEP)<span class="sc">/</span>FGA, <span class="dv">3</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb60-3"><a href="exploratory-data-analysis.html#cb60-3" aria-hidden="true" tabindex="-1"></a>TOVPCT <span class="ot">&lt;-</span> <span class="fu">round</span>(TOV<span class="sc">/</span>(FGA <span class="sc">+</span> <span class="fl">0.44</span> <span class="sc">*</span> FTA <span class="sc">+</span> TOV), <span class="dv">3</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb60-4"><a href="exploratory-data-analysis.html#cb60-4" aria-hidden="true" tabindex="-1"></a>ORBPCT <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">c</span>(ORB[<span class="dv">1</span>]<span class="sc">/</span>(ORB[<span class="dv">1</span>] <span class="sc">+</span> DRB[<span class="dv">2</span>]), ORB[<span class="dv">2</span>]<span class="sc">/</span>(ORB[<span class="dv">2</span>] <span class="sc">+</span> DRB[<span class="dv">1</span>])), <span class="dv">3</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb60-5"><a href="exploratory-data-analysis.html#cb60-5" aria-hidden="true" tabindex="-1"></a>FTFACTOR <span class="ot">&lt;-</span> <span class="fu">round</span>(FT<span class="sc">/</span>FGA, <span class="dv">3</span>) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb60-6"><a href="exploratory-data-analysis.html#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="exploratory-data-analysis.html#cb60-7" aria-hidden="true" tabindex="-1"></a>basketball_data <span class="sc">%&gt;%</span></span>
<span id="cb60-8"><a href="exploratory-data-analysis.html#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_column</span>(eFG, TOVPCT, ORBPCT, FTFACTOR)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 13
##   team     FG   FGA THREEP    FT   FTA   ORB   DRB   TOV   eFG TOVPCT ORBPCT
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 CSU      14    48      5    10    14     2    31     5  34.4    8.5    6.2
## 2 WYO      15    60      4     4     4    14    30    12  28.3   16.3   31.1
## # … with 1 more variable: FTFACTOR &lt;dbl&gt;</code></pre>
<p>While this method does produce Four Factors data, it could be difficult to scale for calculating the same statistics for a sample of several games. In the next section, we will introduce an <code>R</code> package that aids in the calculation of Four Factors.</p>
</div>
<div id="basketballanalyzer-four-factors" class="section level3 hasAnchor" number="1.6.4">
<h3><span class="header-section-number">1.6.4</span> BasketballAnalyzeR Four Factors<a href="exploratory-data-analysis.html#basketballanalyzer-four-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The authors of “Basketball Data Science With Applications in R” developed the <code>BasketballAnalyzeR</code> package to be used in conjunction with the book. <code>BasketballAnalyzeR</code> includes built-in datasets from the 2017-18 NBA season and provides many functions for analyzing and plotting basketball data. One such function is <code>fourfactors</code>, which offers a simpler way to perform a four factors analysis.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="exploratory-data-analysis.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;BasketballAnalyzeR&quot;</span>)</span>
<span id="cb62-2"><a href="exploratory-data-analysis.html#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="exploratory-data-analysis.html#cb62-3" aria-hidden="true" tabindex="-1"></a>teams <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;DEN&quot;</span>, <span class="st">&quot;CLE&quot;</span>, <span class="st">&quot;GSW&quot;</span>)  <span class="co">#Nuggets, Cavaliers, Warriors</span></span>
<span id="cb62-4"><a href="exploratory-data-analysis.html#cb62-4" aria-hidden="true" tabindex="-1"></a>team_data <span class="ot">&lt;-</span> <span class="fu">which</span>(Tadd<span class="sc">$</span>team <span class="sc">%in%</span> teams)</span>
<span id="cb62-5"><a href="exploratory-data-analysis.html#cb62-5" aria-hidden="true" tabindex="-1"></a>four_factors_teams <span class="ot">&lt;-</span> <span class="fu">fourfactors</span>(Tbox[team_data, ], Obox[team_data, ])</span>
<span id="cb62-6"><a href="exploratory-data-analysis.html#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(four_factors_teams)</span></code></pre></div>
<pre><code>##                    Team POSS.Off POSS.Def PACE.Off PACE.Def   ORtg   DRtg
## 1   Cleveland Cavaliers  8221.96  8229.72 2.083619 2.085585 110.57 109.53
## 2        Denver Nuggets  8232.20  8179.24 2.070473 2.057153 109.57 108.80
## 3 Golden State Warriors  8287.92  8457.08 2.100335 2.143203 112.26 104.22
##   F1.Off F2.Off F3.Off F4.Off F1.Def F2.Def F3.Def F4.Def
## 1  54.70  13.70  20.06  21.41  53.98  13.43  77.27  16.58
## 2  53.62  14.90  25.66  19.77  53.88  13.83  77.45  17.35
## 3  56.91  15.26  21.05  19.48  50.44  13.89  76.31  18.55</code></pre>
<p>This is a much simpler and neater way to calculate Four Factors.</p>
<p>In the 2017-18 season, the Warriors and Cavaliers met in the NBA Finals, while the Nuggets just missed the playoffs. It would be expected that the two Finals teams would have higher values for the Four Factors. While this is mostly true, for which of the Four Factors did the Nuggets have the highest value?</p>
<p>A: Factor 3 (rebounding percentage), both offensive and defensive.</p>
</div>
<div id="basketballanalyzer-shot-charts" class="section level3 hasAnchor" number="1.6.5">
<h3><span class="header-section-number">1.6.5</span> BasketballAnalyzeR Shot Charts<a href="exploratory-data-analysis.html#basketballanalyzer-shot-charts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>BasketballAnalyzeR</code> package includes shot location data for all players for the 2017-18 NBA season and has a function called <code>shotchart</code> that allows for the plotting of shot data.</p>
<p>Let’s plot shot location data for Nikola Jokic. First, the coordinates must be transformed so that the point (0,0) is located at the corner of the court; the original coordinates place the origin at the center of the hoop.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="exploratory-data-analysis.html#cb64-1" aria-hidden="true" tabindex="-1"></a>PbP <span class="ot">&lt;-</span> <span class="fu">PbPmanipulation</span>(PbP.BDB)</span>
<span id="cb64-2"><a href="exploratory-data-analysis.html#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="exploratory-data-analysis.html#cb64-3" aria-hidden="true" tabindex="-1"></a>jokic_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(PbP, player <span class="sc">==</span> <span class="st">&quot;Nikola Jokic&quot;</span>)</span>
<span id="cb64-4"><a href="exploratory-data-analysis.html#cb64-4" aria-hidden="true" tabindex="-1"></a>jokic_data<span class="sc">$</span>xx <span class="ot">&lt;-</span> jokic_data<span class="sc">$</span>original_x<span class="sc">/</span><span class="dv">10</span>  <span class="co">#transformation</span></span>
<span id="cb64-5"><a href="exploratory-data-analysis.html#cb64-5" aria-hidden="true" tabindex="-1"></a>jokic_data<span class="sc">$</span>yy <span class="ot">&lt;-</span> jokic_data<span class="sc">$</span>original_y<span class="sc">/</span><span class="dv">10</span> <span class="sc">-</span> <span class="fl">41.75</span>  <span class="co">#transformation</span></span></code></pre></div>
<p><code>BasketballAnalyzeR</code> supports three types of density visualizations within <code>shotchart</code>, one being <code>density-polygons</code>. Since <code>shotchart</code> is a <code>ggplot</code> object, a chart title can be added using <code>ggtitle</code>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="exploratory-data-analysis.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> jokic_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-polygons&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Nikola Jokic Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%203-1.png" width="672" /></p>
<p>It seems most shots attempts from Jokic were in the paint; this is hardly surprising, since he plays the center position. Here’s the same chart with <code>density-hexbin</code>:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="exploratory-data-analysis.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> jokic_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-hexbin&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Nikola Jokic Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%204-1.png" width="672" /></p>
<p>The same chart with <code>density-raster</code>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="exploratory-data-analysis.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> jokic_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-raster&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Nikola Jokic Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%205-1.png" width="672" /></p>
<p>Within the <code>shotchart</code> function, setting <code>scatter=TRUE</code> overlays the shots on the chart. Point size and transparency can also be customized.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="exploratory-data-analysis.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> jokic_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-raster&quot;</span>, <span class="at">scatter =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb68-2"><a href="exploratory-data-analysis.html#cb68-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Nikola Jokic Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%206-1.png" width="672" /></p>
<p>Let’s now compare shot charts of Nikola Jokic, Steph Curry, and Lebron James. This group of players includes one member of each team for which we calculated Four Factors.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="exploratory-data-analysis.html#cb69-1" aria-hidden="true" tabindex="-1"></a>curry_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(PbP, player <span class="sc">==</span> <span class="st">&quot;Stephen Curry&quot;</span>)</span>
<span id="cb69-2"><a href="exploratory-data-analysis.html#cb69-2" aria-hidden="true" tabindex="-1"></a>curry_data<span class="sc">$</span>xx <span class="ot">&lt;-</span> curry_data<span class="sc">$</span>original_x<span class="sc">/</span><span class="dv">10</span>  <span class="co">#transformation</span></span>
<span id="cb69-3"><a href="exploratory-data-analysis.html#cb69-3" aria-hidden="true" tabindex="-1"></a>curry_data<span class="sc">$</span>yy <span class="ot">&lt;-</span> curry_data<span class="sc">$</span>original_y<span class="sc">/</span><span class="dv">10</span> <span class="sc">-</span> <span class="fl">41.75</span>  <span class="co">#transformation</span></span>
<span id="cb69-4"><a href="exploratory-data-analysis.html#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="exploratory-data-analysis.html#cb69-5" aria-hidden="true" tabindex="-1"></a>james_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(PbP, player <span class="sc">==</span> <span class="st">&quot;LeBron James&quot;</span>)</span>
<span id="cb69-6"><a href="exploratory-data-analysis.html#cb69-6" aria-hidden="true" tabindex="-1"></a>james_data<span class="sc">$</span>xx <span class="ot">&lt;-</span> james_data<span class="sc">$</span>original_x<span class="sc">/</span><span class="dv">10</span>  <span class="co">#transformation</span></span>
<span id="cb69-7"><a href="exploratory-data-analysis.html#cb69-7" aria-hidden="true" tabindex="-1"></a>james_data<span class="sc">$</span>yy <span class="ot">&lt;-</span> james_data<span class="sc">$</span>original_y<span class="sc">/</span><span class="dv">10</span> <span class="sc">-</span> <span class="fl">41.75</span>  <span class="co">#transformation</span></span>
<span id="cb69-8"><a href="exploratory-data-analysis.html#cb69-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-9"><a href="exploratory-data-analysis.html#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> jokic_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-raster&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Nikola Jokic Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%207-1.png" width="672" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="exploratory-data-analysis.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> curry_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-raster&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Steph Curry Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%207-2.png" width="672" /></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="exploratory-data-analysis.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> james_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">type =</span> <span class="st">&quot;density-raster&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Lebron James Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%207-3.png" width="672" /></p>
<p>Q: Of the three players (Jokic, Curry, James), which took the highest percentage of their three-point shots from the right side of the court (when facing the basket)?</p>
<p>A: Nikola Jokic shot almost all of his attempts from the right side. Steph Curry took many shots from beyond the arc and tended toward the left side, while James was split between the right side and the center.</p>
<p>Now, let’s focus on Steph Curry’s shooting. The following chart splits the court into zones based on angle and distance from the basket. The color in each zone represents the average length of the play leading up to that shot among shots taken in that zone.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="exploratory-data-analysis.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shotchart</span>(<span class="at">data =</span> curry_data, <span class="at">x =</span> <span class="st">&quot;xx&quot;</span>, <span class="at">y =</span> <span class="st">&quot;yy&quot;</span>, <span class="at">z =</span> <span class="st">&quot;playlength&quot;</span>, <span class="at">type =</span> <span class="st">&quot;sectors&quot;</span>,</span>
<span id="cb72-2"><a href="exploratory-data-analysis.html#cb72-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">num.sect =</span> <span class="dv">7</span>, <span class="at">scatter =</span> <span class="cn">TRUE</span>, <span class="at">pt.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Steph Curry Shot Data, 2017-18&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/basketballanalyzer%208-1.png" width="672" /></p>
<p>Q: In general, did Steph Curry tend to shoot closer to the basket during plays of a longer duration or a shorter duration?</p>
<p>A: There is not a perfect correlation, but it seems that two-point field goals were attempted more often during longer plays, while shots taken outside the three-point arc were taken during plays of a shorter duration.</p>
<p><em>References: <a href="https://rdrr.io/cran/BasketballAnalyzeR/" class="uri">https://rdrr.io/cran/BasketballAnalyzeR/</a>; Basketball Data Science (Zuccolotto and Manisera, 2020)</em></p>
<div style="page-break-after: always;"></div>
</div>
</div>
<div id="soccer" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Soccer<a href="exploratory-data-analysis.html#soccer" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To begin, let’s go over a couple of basic summary statistics specific to soccer that will be necessary to understand for the following examples.</p>
<ul>
<li><p><strong>Shots (SH)</strong> represent all shots taken by a team throughout the game. This is simply an attempt by a player to shoot the ball toward the net, even if they miss or the shot is saved (Rookie Road).</p></li>
<li><p><strong>Shots on Goal (SOG)</strong> represent all shots that would have gone into the goal if not saved by a defender or goalkeeper (Rookie Road).</p></li>
<li><p><strong>Expected Goals (xG)</strong> “indicates how many goals a team could have expected to score based on the quantity and quality of chances that they created in a match” (Tippett 2019, 4).</p></li>
<li><p><strong>Assist (A)</strong> occur when a player passes the ball to someone, and the next shot results in a goal.</p></li>
<li><p><strong>Possession</strong> refers to the percentage of time a team had control of the ball during a game.</p></li>
</ul>
<p>These definitions come from www.rookieroad.com and “The Expected Goals Philosophy” by James Tippett.</p>
<p>To learn more about expected goals, check out <a href="https://www.youtube.com/watch?v=w7zPZsLGK18&amp;list=PL9Az6mi38hv__afKnHR1AKjpcDIw_0qqT" class="uri">this YouTube video</a>.</p>
<div id="bar-plot" class="section level3 hasAnchor" number="1.7.1">
<h3><span class="header-section-number">1.7.1</span> Bar Plot<a href="exploratory-data-analysis.html#bar-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have an understanding of some basic shooting statistics, let us go through some EDA examples. For this first example, we will need to install the “worldfootballR” package.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="exploratory-data-analysis.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(worldfootballR)</span></code></pre></div>
<p>Next we will look at some data specific to LaLiga, which is a soccer league in the men’s top professional soccer division.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="exploratory-data-analysis.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get &#39;Squad Standard Stats&#39; Data</span></span>
<span id="cb74-2"><a href="exploratory-data-analysis.html#cb74-2" aria-hidden="true" tabindex="-1"></a>big5_2021_stats <span class="ot">&lt;-</span> <span class="fu">fb_big5_advanced_season_stats</span>(<span class="at">season_end_year =</span> <span class="dv">2021</span>, <span class="at">stat_type =</span> <span class="st">&quot;standard&quot;</span>,</span>
<span id="cb74-3"><a href="exploratory-data-analysis.html#cb74-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">team_or_player =</span> <span class="st">&quot;team&quot;</span>)</span>
<span id="cb74-4"><a href="exploratory-data-analysis.html#cb74-4" aria-hidden="true" tabindex="-1"></a>liga_2021_stats <span class="ot">&lt;-</span> big5_2021_stats[<span class="fu">which</span>((big5_2021_stats<span class="sc">$</span>Comp <span class="sc">==</span> <span class="st">&quot;La Liga&quot;</span>)), ]</span></code></pre></div>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="exploratory-data-analysis.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create visual for each team&#39;s goals per game</span></span>
<span id="cb75-2"><a href="exploratory-data-analysis.html#cb75-2" aria-hidden="true" tabindex="-1"></a>team_goals_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> liga_2021_stats[<span class="fu">which</span>(liga_2021_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span></span>
<span id="cb75-3"><a href="exploratory-data-analysis.html#cb75-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;team&quot;</span>), ], <span class="fu">aes</span>(<span class="at">x =</span> Squad, <span class="at">y =</span> Gls_Per)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span>
<span id="cb75-4"><a href="exploratory-data-analysis.html#cb75-4" aria-hidden="true" tabindex="-1"></a>team_goals_viz</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>This plot is a good starting point, but still looks pretty messy. Let’s add a title, change the axis titles, and rotate the axis labels so they are not overlapping over one another.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="exploratory-data-analysis.html#cb76-1" aria-hidden="true" tabindex="-1"></a>team_goals_viz <span class="ot">&lt;-</span> team_goals_viz <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Team&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Goals Per Game&quot;</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb76-2"><a href="exploratory-data-analysis.html#cb76-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Goals Per Game by Team&quot;</span>)</span>
<span id="cb76-3"><a href="exploratory-data-analysis.html#cb76-3" aria-hidden="true" tabindex="-1"></a>team_goals_viz</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>This is already looking a lot better. Now, we will add the goals scored per game <em>against</em> each team. Why is this of interest? Well, at first glance, Barcelona seems like a pretty impressive team, as they score more goals per game than any other team in the league. However, what if they also have more goals scored against them than any other team in the league? This could be important context, so we will include it in the graph below.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="exploratory-data-analysis.html#cb77-1" aria-hidden="true" tabindex="-1"></a>all_goals_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> liga_2021_stats, <span class="fu">aes</span>(<span class="at">x =</span> Squad, <span class="at">y =</span> Gls_Per)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>,</span>
<span id="cb77-2"><a href="exploratory-data-analysis.html#cb77-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">fill =</span> Team_or_Opponent), <span class="at">position =</span> <span class="st">&quot;stack&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Team&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Goals Per 90 Minutes&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-3"><a href="exploratory-data-analysis.html#cb77-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Goals Per Game by Team&quot;</span>)</span>
<span id="cb77-4"><a href="exploratory-data-analysis.html#cb77-4" aria-hidden="true" tabindex="-1"></a>all_goals_viz</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>This is looking pretty good, but let’s clean it up just a bit by changing the legend title and labels.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="exploratory-data-analysis.html#cb78-1" aria-hidden="true" tabindex="-1"></a>all_goals_viz <span class="sc">+</span> <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">&quot;Team or Opponent&quot;</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Opponent&quot;</span>,</span>
<span id="cb78-2"><a href="exploratory-data-analysis.html#cb78-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Team&quot;</span>))</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>What does this graph show us? Well, we are able to see the average number of goals scored for and against each team per game. It looks like Barcelona is scoring a lot more goals than they are letting be scored against them, while other teams like Valladolid tend to have a higher proportion of goals scored for the opposing team.</p>
</div>
<div id="scatter-plot" class="section level3 hasAnchor" number="1.7.2">
<h3><span class="header-section-number">1.7.2</span> Scatter Plot<a href="exploratory-data-analysis.html#scatter-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In addition to simply knowing the average actual number of goals scored for and against each team per game, we may be interested in how this compares to the expected number of goals scored per game, as well.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="exploratory-data-analysis.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggExtra)</span>
<span id="cb79-2"><a href="exploratory-data-analysis.html#cb79-2" aria-hidden="true" tabindex="-1"></a>act_exp_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> liga_2021_stats, <span class="fu">aes</span>(<span class="at">x =</span> xG_Per, <span class="at">y =</span> Gls_Per, <span class="at">label =</span> Squad)) <span class="sc">+</span></span>
<span id="cb79-3"><a href="exploratory-data-analysis.html#cb79-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">2.25</span>)) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.75</span>,</span>
<span id="cb79-4"><a href="exploratory-data-analysis.html#cb79-4" aria-hidden="true" tabindex="-1"></a>    <span class="fl">2.25</span>)) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Expected vs. Actual Goals Per Game&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Expected Goals Per Game&quot;</span>) <span class="sc">+</span></span>
<span id="cb79-5"><a href="exploratory-data-analysis.html#cb79-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Actual Goals Per Game&quot;</span>) <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb79-6"><a href="exploratory-data-analysis.html#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggMarginal</span>(act_exp_viz, <span class="at">type =</span> <span class="st">&quot;density&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>As you can see, we fit a line to the data. At first glance, it seems to have a positive slope slightly greater than 1. What does this mean in the scenario of actual and expected goals per game?</p>
</div>
<div id="density-ridges-plot" class="section level3 hasAnchor" number="1.7.3">
<h3><span class="header-section-number">1.7.3</span> Density Ridges Plot<a href="exploratory-data-analysis.html#density-ridges-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>At first glance, it seems that actual goals scored per game do not differ greatly from expected goals per game. Let us look at some density plots for actual and expected goals per game for five of the top teams in LaLiga over the last four seasons. These are the top five teams as of June 21st, 2022 on www.foxsports.com.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="exploratory-data-analysis.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb80-2"><a href="exploratory-data-analysis.html#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="exploratory-data-analysis.html#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get &#39;Squad Standard Stats&#39; data for the last four seasons</span></span>
<span id="cb80-4"><a href="exploratory-data-analysis.html#cb80-4" aria-hidden="true" tabindex="-1"></a>top_liga_2021_stats <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/laliga21.csv&quot;</span>)</span>
<span id="cb80-5"><a href="exploratory-data-analysis.html#cb80-5" aria-hidden="true" tabindex="-1"></a>top_liga_2020_stats <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/laliga20.csv&quot;</span>)</span>
<span id="cb80-6"><a href="exploratory-data-analysis.html#cb80-6" aria-hidden="true" tabindex="-1"></a>top_liga_2019_stats <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/laliga19.csv&quot;</span>)</span>
<span id="cb80-7"><a href="exploratory-data-analysis.html#cb80-7" aria-hidden="true" tabindex="-1"></a>top_liga_2018_stats <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/laliga18.csv&quot;</span>)</span>
<span id="cb80-8"><a href="exploratory-data-analysis.html#cb80-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-9"><a href="exploratory-data-analysis.html#cb80-9" aria-hidden="true" tabindex="-1"></a>top_liga_2021_stats <span class="ot">&lt;-</span> top_liga_2021_stats[<span class="fu">which</span>(top_liga_2021_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Real Madrid&quot;</span> <span class="sc">|</span></span>
<span id="cb80-10"><a href="exploratory-data-analysis.html#cb80-10" aria-hidden="true" tabindex="-1"></a>    top_liga_2021_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Villarreal&quot;</span> <span class="sc">|</span> top_liga_2021_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Barcelona&quot;</span> <span class="sc">|</span></span>
<span id="cb80-11"><a href="exploratory-data-analysis.html#cb80-11" aria-hidden="true" tabindex="-1"></a>    top_liga_2021_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Levante&quot;</span> <span class="sc">|</span> top_liga_2021_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Betis&quot;</span>),</span>
<span id="cb80-12"><a href="exploratory-data-analysis.html#cb80-12" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb80-13"><a href="exploratory-data-analysis.html#cb80-13" aria-hidden="true" tabindex="-1"></a>top_liga_2020_stats <span class="ot">&lt;-</span> top_liga_2020_stats[<span class="fu">which</span>(top_liga_2020_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Real Madrid&quot;</span> <span class="sc">|</span></span>
<span id="cb80-14"><a href="exploratory-data-analysis.html#cb80-14" aria-hidden="true" tabindex="-1"></a>    top_liga_2020_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Villarreal&quot;</span> <span class="sc">|</span> top_liga_2020_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Barcelona&quot;</span> <span class="sc">|</span></span>
<span id="cb80-15"><a href="exploratory-data-analysis.html#cb80-15" aria-hidden="true" tabindex="-1"></a>    top_liga_2020_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Levante&quot;</span> <span class="sc">|</span> top_liga_2020_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Betis&quot;</span>),</span>
<span id="cb80-16"><a href="exploratory-data-analysis.html#cb80-16" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb80-17"><a href="exploratory-data-analysis.html#cb80-17" aria-hidden="true" tabindex="-1"></a>top_liga_2019_stats <span class="ot">&lt;-</span> top_liga_2019_stats[<span class="fu">which</span>(top_liga_2019_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Real Madrid&quot;</span> <span class="sc">|</span></span>
<span id="cb80-18"><a href="exploratory-data-analysis.html#cb80-18" aria-hidden="true" tabindex="-1"></a>    top_liga_2019_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Villarreal&quot;</span> <span class="sc">|</span> top_liga_2019_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Barcelona&quot;</span> <span class="sc">|</span></span>
<span id="cb80-19"><a href="exploratory-data-analysis.html#cb80-19" aria-hidden="true" tabindex="-1"></a>    top_liga_2019_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Levante&quot;</span> <span class="sc">|</span> top_liga_2019_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Betis&quot;</span>),</span>
<span id="cb80-20"><a href="exploratory-data-analysis.html#cb80-20" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb80-21"><a href="exploratory-data-analysis.html#cb80-21" aria-hidden="true" tabindex="-1"></a>top_liga_2018_stats <span class="ot">&lt;-</span> top_liga_2018_stats[<span class="fu">which</span>(top_liga_2018_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Real Madrid&quot;</span> <span class="sc">|</span></span>
<span id="cb80-22"><a href="exploratory-data-analysis.html#cb80-22" aria-hidden="true" tabindex="-1"></a>    top_liga_2018_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Villarreal&quot;</span> <span class="sc">|</span> top_liga_2018_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Barcelona&quot;</span> <span class="sc">|</span></span>
<span id="cb80-23"><a href="exploratory-data-analysis.html#cb80-23" aria-hidden="true" tabindex="-1"></a>    top_liga_2018_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Levante&quot;</span> <span class="sc">|</span> top_liga_2018_stats<span class="sc">$</span>Squad <span class="sc">==</span> <span class="st">&quot;Betis&quot;</span>),</span>
<span id="cb80-24"><a href="exploratory-data-analysis.html#cb80-24" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb80-25"><a href="exploratory-data-analysis.html#cb80-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-26"><a href="exploratory-data-analysis.html#cb80-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all four seasons&#39; data into one data frame</span></span>
<span id="cb80-27"><a href="exploratory-data-analysis.html#cb80-27" aria-hidden="true" tabindex="-1"></a>top_liga_stats <span class="ot">&lt;-</span> <span class="fu">rbind</span>(top_liga_2018_stats, top_liga_2019_stats, top_liga_2020_stats,</span>
<span id="cb80-28"><a href="exploratory-data-analysis.html#cb80-28" aria-hidden="true" tabindex="-1"></a>    top_liga_2021_stats)</span>
<span id="cb80-29"><a href="exploratory-data-analysis.html#cb80-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-30"><a href="exploratory-data-analysis.html#cb80-30" aria-hidden="true" tabindex="-1"></a>goals_act <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(top_liga_stats<span class="sc">$</span>Gls_Per[<span class="fu">which</span>(top_liga_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span></span>
<span id="cb80-31"><a href="exploratory-data-analysis.html#cb80-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;team&quot;</span>)])</span>
<span id="cb80-32"><a href="exploratory-data-analysis.html#cb80-32" aria-hidden="true" tabindex="-1"></a>goals_act<span class="sc">$</span>team <span class="ot">&lt;-</span> top_liga_stats<span class="sc">$</span>Squad[<span class="fu">which</span>(top_liga_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span> <span class="st">&quot;team&quot;</span>)]</span>
<span id="cb80-33"><a href="exploratory-data-analysis.html#cb80-33" aria-hidden="true" tabindex="-1"></a>goals_act<span class="sc">$</span>exp_or_act <span class="ot">&lt;-</span> <span class="st">&quot;actual&quot;</span></span>
<span id="cb80-34"><a href="exploratory-data-analysis.html#cb80-34" aria-hidden="true" tabindex="-1"></a>goals_act<span class="sc">$</span>year <span class="ot">&lt;-</span> top_liga_stats<span class="sc">$</span>Season_End_Year[<span class="fu">which</span>(top_liga_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span></span>
<span id="cb80-35"><a href="exploratory-data-analysis.html#cb80-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;team&quot;</span>)]</span>
<span id="cb80-36"><a href="exploratory-data-analysis.html#cb80-36" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(goals_act)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;stats&quot;</span></span>
<span id="cb80-37"><a href="exploratory-data-analysis.html#cb80-37" aria-hidden="true" tabindex="-1"></a>goals_exp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(top_liga_stats<span class="sc">$</span>xG_Per[<span class="fu">which</span>(top_liga_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span></span>
<span id="cb80-38"><a href="exploratory-data-analysis.html#cb80-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;team&quot;</span>)])</span>
<span id="cb80-39"><a href="exploratory-data-analysis.html#cb80-39" aria-hidden="true" tabindex="-1"></a>goals_exp<span class="sc">$</span>team <span class="ot">&lt;-</span> top_liga_stats<span class="sc">$</span>Squad[<span class="fu">which</span>(top_liga_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span> <span class="st">&quot;team&quot;</span>)]</span>
<span id="cb80-40"><a href="exploratory-data-analysis.html#cb80-40" aria-hidden="true" tabindex="-1"></a>goals_exp<span class="sc">$</span>exp_or_act <span class="ot">&lt;-</span> <span class="st">&quot;expected&quot;</span></span>
<span id="cb80-41"><a href="exploratory-data-analysis.html#cb80-41" aria-hidden="true" tabindex="-1"></a>goals_exp<span class="sc">$</span>year <span class="ot">&lt;-</span> top_liga_stats<span class="sc">$</span>Season_End_Year[<span class="fu">which</span>(top_liga_stats<span class="sc">$</span>Team_or_Opponent <span class="sc">==</span></span>
<span id="cb80-42"><a href="exploratory-data-analysis.html#cb80-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;team&quot;</span>)]</span>
<span id="cb80-43"><a href="exploratory-data-analysis.html#cb80-43" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(goals_exp)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;stats&quot;</span></span>
<span id="cb80-44"><a href="exploratory-data-analysis.html#cb80-44" aria-hidden="true" tabindex="-1"></a>goals <span class="ot">&lt;-</span> <span class="fu">rbind</span>(goals_act, goals_exp)</span>
<span id="cb80-45"><a href="exploratory-data-analysis.html#cb80-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-46"><a href="exploratory-data-analysis.html#cb80-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot density ridges</span></span>
<span id="cb80-47"><a href="exploratory-data-analysis.html#cb80-47" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> goals) <span class="sc">+</span> <span class="fu">geom_density_ridges</span>(<span class="fu">aes</span>(<span class="at">x =</span> stats, <span class="at">y =</span> team, <span class="at">fill =</span> exp_or_act,</span>
<span id="cb80-48"><a href="exploratory-data-analysis.html#cb80-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> exp_or_act), <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">scale =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.75</span>,</span>
<span id="cb80-49"><a href="exploratory-data-analysis.html#cb80-49" aria-hidden="true" tabindex="-1"></a>    <span class="fl">2.75</span>)) <span class="sc">+</span> <span class="fu">scale_y_discrete</span>(<span class="at">expand =</span> <span class="fu">expand_scale</span>(<span class="at">add =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="dv">1</span>))) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Expected vs. Actual Goals Per Game&quot;</span>) <span class="sc">+</span></span>
<span id="cb80-50"><a href="exploratory-data-analysis.html#cb80-50" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Goals Per Game&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Team&quot;</span>) <span class="sc">+</span> <span class="fu">scale_fill_cyclical</span>(<span class="at">name =</span> <span class="st">&quot;Actual or Expected Goals&quot;</span>,</span>
<span id="cb80-51"><a href="exploratory-data-analysis.html#cb80-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual&quot;</span>, <span class="st">&quot;Expected&quot;</span>), <span class="at">guide =</span> <span class="st">&quot;legend&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#FF0000A0&quot;</span>, <span class="st">&quot;#A0A0A0A0&quot;</span>)) <span class="sc">+</span></span>
<span id="cb80-52"><a href="exploratory-data-analysis.html#cb80-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_cyclical</span>(<span class="at">name =</span> <span class="st">&quot;Actual or Expected Goals&quot;</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual&quot;</span>,</span>
<span id="cb80-53"><a href="exploratory-data-analysis.html#cb80-53" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;Expected&quot;</span>), <span class="at">guide =</span> <span class="st">&quot;legend&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#FF0000A0&quot;</span>, <span class="st">&quot;#A0A0A0A0&quot;</span>))</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Let us break down exactly what this visual is showing us. We are looking at the density of expected and actual goals per game for the top five teams in LaLiga, over the last four seasons (with the last season ending in 2021). We can see that Barcelona is typically scoring more goals than what is expected of them, as the density of actual goals is condensed around higher goal numbers than the density of expected goals. Villarreal, however, is performing just as well as what is expected of them based on expected and actual goals scored.</p>
<div style="page-break-after: always;"></div>
</div>
</div>
<div id="hockey" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Hockey<a href="exploratory-data-analysis.html#hockey" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://www.youtube.com/watch?v=nv2FUnHceqU">Link to YouTube video describing hockey rules</a></p>
<div id="basic-hockey-statistics" class="section level3 hasAnchor" number="1.8.1">
<h3><span class="header-section-number">1.8.1</span> Basic Hockey Statistics<a href="exploratory-data-analysis.html#basic-hockey-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Here are some basic statistics that are used often to describe hockey games.</p>
<ul>
<li><p><strong>Goals (G)</strong>: If a team scores, the skater on the scoring team who last touched the puck is credited with a goal.</p></li>
<li><p><strong>Assists (A)</strong>: The players (up to two) on the scoring team who last touch the puck before the goalscorer are credited with assists, unless the opposing team has possession of the puck in between.</p></li>
<li><p><strong>Points (PTS)</strong>: Goals plus assists. [Not to be confused with team points awarded in the regular season standings by the many hockey leagues, including the NHL (two points for a win, one point for an overtime/shootout loss, zero points for a regulation loss)].</p></li>
<li><p><strong>Shots On Goal (SOG)</strong>: Shot attempts in which the puck has been shot directly on goal. Shot attempts which are blocked or miss the goal are not considered SOGs. A team’s shots on goal should equal the opposing goaltender’s saves plus the team’s goals scored.</p></li>
<li><p><strong>Goals Against Average (GAA)</strong>: Of a goaltender, the number of goals allowed by that goaltender adjusted to a per-60 minute rate.</p></li>
<li><p><strong>Penalty Minutes (PIM)</strong>: The amount of penalty time an individual player is assigned for their infractions. PIM may be different than the amount of time the player actually spends in the penalty box.</p></li>
</ul>
<p><em>Reference: <a href="https://www.milehighhockey.com/pages/stats" class="uri">https://www.milehighhockey.com/pages/stats</a></em></p>
</div>
<div id="advanced-hockey-statistics" class="section level3 hasAnchor" number="1.8.2">
<h3><span class="header-section-number">1.8.2</span> Advanced Hockey Statistics<a href="exploratory-data-analysis.html#advanced-hockey-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>CORSI</strong>: CORSI only applies to 5 on 5 (“even-strength”) situations. It is calculated as the difference between shot attempts on offense (shots on goal + blocked shots + missed shots) minus shot attempts allowed on defense. CORSI can also be expressed as a percentage, with percentages over 50% indicating that the player is on ice for more offensive shots than defensive shots.</p></li>
<li><p><strong>Expected Goals (xG)</strong>: Expected Goals statistics give each shot an estimated probability of scoring a goal based on factors such as shot location and game situation. xG cannot be less than 0 or greater than 1 for any particular shot, and different platforms may have different methods of calculating expected goals.</p></li>
<li><p><strong>Fenwick/Unblocked Shot Attempts (USAT)</strong>: Similar to CORSI, but omits blocked shots from the calculation. This statistic is used in many Expected Goals calculations.</p></li>
</ul>
<p>Because the flow of a hockey game is usually quite different in situations other than the normal 5 on 5, such as a power play (5 on 4) or concurrent penalties (4 on 4), many hockey databases separate data by the type of game situation. We will see this below with a dataset from <a href="www.moneypuck.com">MoneyPuck</a>, but it is also present on <a href="https://www.naturalstattrick.com/">Natural Stat Trick</a>, <a href="www.quanthockey.com">QuantHockey</a>, and <a href="www.hockey-reference.com">hockey-reference</a>.</p>
<p><em>References: <a href="https://www.nhl.com/lightning/news/hockey-analytics-101-understanding-advanced-stats-and-how-theyre-measured/c-735819" class="uri">https://www.nhl.com/lightning/news/hockey-analytics-101-understanding-advanced-stats-and-how-theyre-measured/c-735819</a>, <a href="https://theathletic.com/121980/2017/10/09/an-advanced-stat-primer-understanding-basic-hockey-metrics/" class="uri">https://theathletic.com/121980/2017/10/09/an-advanced-stat-primer-understanding-basic-hockey-metrics/</a></em></p>
</div>
<div id="actual-vs.-expected-goals" class="section level3 hasAnchor" number="1.8.3">
<h3><span class="header-section-number">1.8.3</span> Actual vs. Expected Goals<a href="exploratory-data-analysis.html#actual-vs.-expected-goals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="example">
<p><span id="exm:unlabeled-div-34" class="example"><strong>Example 1.10  </strong></span>For this example, we’ll use a set of NHL data from moneypuck.com. First, let’s load the data into <code>R</code> and open the data frame.</p>
</div>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="exploratory-data-analysis.html#cb81-1" aria-hidden="true" tabindex="-1"></a>nhl_2022_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://moneypuck.com/moneypuck/playerData/seasonSummary/2021/regular/teams.csv&quot;</span>)</span>
<span id="cb81-2"><a href="exploratory-data-analysis.html#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="exploratory-data-analysis.html#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nhl_2022_data)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 107
##   team...1 season name  team...4 position   situation games_played
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;
## 1 WPG        2021 WPG   WPG      Team Level other               82
## 2 WPG        2021 WPG   WPG      Team Level all                 82
## 3 WPG        2021 WPG   WPG      Team Level 5on5                82
## 4 WPG        2021 WPG   WPG      Team Level 4on5                82
## 5 WPG        2021 WPG   WPG      Team Level 5on4                82
## 6 CBJ        2021 CBJ   CBJ      Team Level other               82
## # … with 100 more variables: xGoalsPercentage &lt;dbl&gt;, corsiPercentage &lt;dbl&gt;,
## #   fenwickPercentage &lt;dbl&gt;, iceTime &lt;dbl&gt;, xOnGoalFor &lt;dbl&gt;, xGoalsFor &lt;dbl&gt;,
## #   xReboundsFor &lt;dbl&gt;, xFreezeFor &lt;dbl&gt;, xPlayStoppedFor &lt;dbl&gt;,
## #   xPlayContinuedInZoneFor &lt;dbl&gt;, xPlayContinuedOutsideZoneFor &lt;dbl&gt;,
## #   flurryAdjustedxGoalsFor &lt;dbl&gt;, scoreVenueAdjustedxGoalsFor &lt;dbl&gt;,
## #   flurryScoreVenueAdjustedxGoalsFor &lt;dbl&gt;, shotsOnGoalFor &lt;dbl&gt;,
## #   missedShotsFor &lt;dbl&gt;, blockedShotAttemptsFor &lt;dbl&gt;, …</code></pre>
<p>We can create nice looking tables using the ``kableExtra’’ package. Let’s look at the first eight rows and a samll selection of columns of the data frame and format the table output using a kable table.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="exploratory-data-analysis.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;kableExtra&quot;</span>)</span>
<span id="cb83-2"><a href="exploratory-data-analysis.html#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="exploratory-data-analysis.html#cb83-3" aria-hidden="true" tabindex="-1"></a>nhl_2022_data[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span><span class="sc">:</span><span class="dv">9</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb83-4"><a href="exploratory-data-analysis.html#cb83-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="exploratory-data-analysis.html#cb83-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
name
</th>
<th style="text-align:left;">
situation
</th>
<th style="text-align:right;">
games_played
</th>
<th style="text-align:right;">
xGoalsPercentage
</th>
<th style="text-align:right;">
corsiPercentage
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
WPG
</td>
<td style="text-align:left;">
other
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.49
</td>
<td style="text-align:right;">
0.50
</td>
</tr>
<tr>
<td style="text-align:left;">
WPG
</td>
<td style="text-align:left;">
all
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.49
</td>
<td style="text-align:right;">
0.50
</td>
</tr>
<tr>
<td style="text-align:left;">
WPG
</td>
<td style="text-align:left;">
5on5
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.49
</td>
<td style="text-align:right;">
0.49
</td>
</tr>
<tr>
<td style="text-align:left;">
WPG
</td>
<td style="text-align:left;">
4on5
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
0.14
</td>
</tr>
<tr>
<td style="text-align:left;">
WPG
</td>
<td style="text-align:left;">
5on4
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.86
</td>
<td style="text-align:right;">
0.86
</td>
</tr>
<tr>
<td style="text-align:left;">
CBJ
</td>
<td style="text-align:left;">
other
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
0.49
</td>
</tr>
<tr>
<td style="text-align:left;">
CBJ
</td>
<td style="text-align:left;">
all
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.48
</td>
</tr>
<tr>
<td style="text-align:left;">
CBJ
</td>
<td style="text-align:left;">
5on5
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.48
</td>
</tr>
</tbody>
</table>
<p>This dataset includes a <em>lot</em> of covariates. It also splits these data by different game situations: even-strength (5 on 5), power play (5 on 4), etc. Let’s subset the data to include all game situations.</p>
<p>Use the <code>nrow</code> command to check the number of columns in the new data frame. Check: Is it the same as the number of teams in the league for the 2021-2022 season?</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="exploratory-data-analysis.html#cb84-1" aria-hidden="true" tabindex="-1"></a>nhl_data_all <span class="ot">&lt;-</span> <span class="fu">filter</span>(nhl_2022_data, situation <span class="sc">==</span> <span class="st">&quot;all&quot;</span>)</span>
<span id="cb84-2"><a href="exploratory-data-analysis.html#cb84-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-3"><a href="exploratory-data-analysis.html#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(nhl_data_all)</span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<p>The dataset includes an Expected Goals statistic for each team in the <code>xGoalsFor</code> column. Let’s plot this quantity against the team’s actual number of goals scored; this is given by the <code>goalsFor</code> column.</p>
<p>(Remember to always have a good title and axis labels!)</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="exploratory-data-analysis.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> nhl_data_all, <span class="fu">aes</span>(<span class="at">x =</span> xGoalsFor, <span class="at">y =</span> goalsFor)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Expected Goals Scored&quot;</span>,</span>
<span id="cb86-2"><a href="exploratory-data-analysis.html#cb86-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Actual Goals Scored&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NHL Teams: Expected vs. Actual Goals, 2021-22&quot;</span>) <span class="sc">+</span></span>
<span id="cb86-3"><a href="exploratory-data-analysis.html#cb86-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>As expected, there is a general positive correlation between expected and actual goals (<span class="math inline">\(r \approx 0.8\)</span>). However, there is some variability - for example, the Kings only scored 7 more actual goals than the Ducks, despite having 56.6 more expected goals.</p>
<p>Let’s add a line to the graph using the <code>geom_abline</code> function corresponding to the line <span class="math inline">\(y=x\)</span>, the line on which data points would fall if expected goals were equal to actual goals. We can also customize the line’s color and type.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="exploratory-data-analysis.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> nhl_data_all, <span class="fu">aes</span>(<span class="at">x =</span> xGoalsFor, <span class="at">y =</span> goalsFor)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Expected Goals Scored&quot;</span>,</span>
<span id="cb87-2"><a href="exploratory-data-analysis.html#cb87-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Actual Goals Scored&quot;</span>, <span class="at">title =</span> <span class="st">&quot;NHL Teams: Expected vs. Actual Goals, 2021-22&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-3"><a href="exploratory-data-analysis.html#cb87-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p><em>Note: A slope of 0 and an intercept of 1 are actually the default parameters for the function.</em></p>
<p>Q: What does it mean for a team’s data point to fall below this line? Above it?</p>
<p>A: If the data point is below the line, it means the expected goals were greater than the actual goals; if the data point is above the line, it means the actual goals were greater than the expected goals.</p>
<p>Q: Do you think that a team’s expected goals would be more likely to be closer to its actual goals for a ten-game stretch, an entire season, or five consecutive seasons? Why?</p>
<!-- Question could be reworded/clarified to mean "closer" in a relative (ratio) sense, rather than an absolute sense. -->
<p>A: We would expect that as sample size increases, the result would become closer to expectation. So, actual goals would be most likely closer to expected goals over a span of five seasons.</p>
<!--- This is basically conceptualizing the LLN, but that would rely on this calculation of expected goals being an unbiased estimator of actual goals. -->
</div>
<div id="goalie-statistics" class="section level3 hasAnchor" number="1.8.4">
<h3><span class="header-section-number">1.8.4</span> Goalie Statistics<a href="exploratory-data-analysis.html#goalie-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="example">
<p><span id="exm:unlabeled-div-35" class="example"><strong>Example 1.11  </strong></span>For this next example, let’s use goalie data from the 2021-2022 season from <a href="https://www.naturalstattrick.com/">Natural Stat Trick</a>.</p>
</div>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="exploratory-data-analysis.html#cb88-1" aria-hidden="true" tabindex="-1"></a>goalie_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/GoalieTotals_NaturalStatTrick.csv&quot;</span>)</span>
<span id="cb88-2"><a href="exploratory-data-analysis.html#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(goalie_data)</span></code></pre></div>
<pre><code>##     X           Player Team GP       TOI Shots.Against Saves Goals.Against
## 1  87 Charlie Lindgren  STL  5 246.41667           118   113             5
## 2  34   Louis Domingue  PIT  2 118.75000            83    79             4
## 3  63   Spencer Martin  VAN  6 378.35000           218   207            11
## 4  37   Michael Houser  BUF  2 120.00000            75    71             4
## 5 100   Daniil Tarasov  CBJ  4 174.85000           111   104             7
## 6  41    Garret Sparks  L.A  2  97.21667            47    44             3
##     SV.  GAA GSAA xG.Against HD.Shots.Against HD.Saves HD.Goals.Against HDSV.
## 1 0.958 1.22 5.97      10.21               29       27                2 0.931
## 2 0.952 2.02 3.72       7.16               25       21                4 0.840
## 3 0.950 1.74 9.27      21.11               62       57                5 0.919
## 4 0.947 2.00 2.97       5.52               14       12                2 0.857
## 5 0.937 2.40 3.32       9.07               31       25                6 0.806
## 6 0.936 1.85 1.37       3.42               12        9                3 0.750
##   HDGAA HDGSAA Rush.Attempts.Against Rebound.Attempts.Against
## 1  0.49   3.32                     2                       13
## 2  2.02   0.58                     7                       13
## 3  0.79   6.37                     8                       27
## 4  1.00   0.57                     2                       10
## 5  2.06  -0.32                     3                       18
## 6  1.85  -0.80                     0                        5
##   Avg..Shot.Distance Avg..Goal.Distance
## 1              36.58              16.40
## 2              36.06               9.00
## 3              33.36              25.09
## 4              37.05              19.50
## 5              37.50              19.71
## 6              32.32              17.33</code></pre>
<p>The dataset includes 119 goalies, but many of them didn’t play very much. We can subset the data to include only goaltenders that faced at least 500 shots.</p>
<p>Which player among qualified goalies had the best goals against average? On which team did he play, and what was his GAA?</p>
<p>Which goalie had the most playing time? What was his team, and how much time did he spend on the ice?</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="exploratory-data-analysis.html#cb90-1" aria-hidden="true" tabindex="-1"></a>filtered_goalie_data <span class="ot">&lt;-</span> <span class="fu">filter</span>(goalie_data, Shots.Against <span class="sc">&gt;=</span> <span class="dv">500</span>)</span>
<span id="cb90-2"><a href="exploratory-data-analysis.html#cb90-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a href="exploratory-data-analysis.html#cb90-3" aria-hidden="true" tabindex="-1"></a>filtered_goalie_data <span class="sc">%&gt;%</span></span>
<span id="cb90-4"><a href="exploratory-data-analysis.html#cb90-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(GAA <span class="sc">==</span> <span class="fu">min</span>(GAA)) <span class="sc">%&gt;%</span></span>
<span id="cb90-5"><a href="exploratory-data-analysis.html#cb90-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Player, Team, GAA)</span></code></pre></div>
<pre><code>##            Player Team  GAA
## 1 Igor Shesterkin  NYR 2.07</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="exploratory-data-analysis.html#cb92-1" aria-hidden="true" tabindex="-1"></a>filtered_goalie_data <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="exploratory-data-analysis.html#cb92-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(TOI <span class="sc">==</span> <span class="fu">max</span>(TOI)) <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="exploratory-data-analysis.html#cb92-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Player, Team, TOI)</span></code></pre></div>
<pre><code>##        Player Team      TOI
## 1 Juuse Saros  NSH 3931.383</code></pre>
<p>The following plot compares save percentage to the number of shots on goal faced for the qualified goalies. The dashed horizontal line is placed at the average shots on goal faced among qualified players, and the dashed vertical line is placed at the average save percentage among qualified players.</p>
<p><img src="series_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Q: Which quadrant of the graph represents goalies that faced a higher than average number of shots, but had a below-average save percentage?</p>
<p>A: The second (upper left) quadrant.</p>
<p>Q: Which quadrant represents goalies that had a high save percentage and faced a high volume of shots?</p>
<p>A: The first (upper right) quadrant.</p>
</div>
<div id="correlation-plots" class="section level3 hasAnchor" number="1.8.5">
<h3><span class="header-section-number">1.8.5</span> Correlation Plots<a href="exploratory-data-analysis.html#correlation-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When analyzing sports data, there may be many circumstances where statisticians consider which of several variables are most highly correlated to an outcome variable of interest. In this case, it can be useful to use a correlation plot (also known as a correlation matrix or correlogram). Tidyverse and related packages provide many options for creating correlation plots.</p>
<p>Suppose a statistician has recently learned about some advanced hockey statistics and is interested in researching which stat has the highest correlation with goals scored. The statistician wants to compare team shots on goal, CORSI, and Fenwick to observe the association with goals scored for NHL teams.</p>
<div class="example">
<p><span id="exm:unlabeled-div-36" class="example"><strong>Example 1.12  </strong></span>The following plot uses the same 2021-2022 data from Moneypuck.com; it gives the pairwise scatterplots and correlation values for each of the variables, as well as smoothed plots of each individual variable along the diagonals.</p>
</div>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="exploratory-data-analysis.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;GGally&quot;</span>)</span>
<span id="cb94-2"><a href="exploratory-data-analysis.html#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="exploratory-data-analysis.html#cb94-3" aria-hidden="true" tabindex="-1"></a>goal_stats <span class="ot">&lt;-</span> nhl_data_all <span class="sc">%&gt;%</span></span>
<span id="cb94-4"><a href="exploratory-data-analysis.html#cb94-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(shotsOnGoalFor, corsiPercentage, fenwickPercentage, goalsFor)</span>
<span id="cb94-5"><a href="exploratory-data-analysis.html#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(goal_stats, <span class="at">title =</span> <span class="st">&quot;Correlation plot of goals and relevant predictors, NHL 2021-22&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Q: Which of the variables has the strongest correlation with goals scored?</p>
<p>A: CORSI percentage, r = .702.</p>
<p>In the article <a href="https://theathletic.com/121980/2017/10/09/an-advanced-stat-primer-understanding-basic-hockey-metrics/">“An advanced stat primer: Understanding basic hockey metrics”</a>, Charlie O’Connor states, “Generally speaking, Corsi is more predictive of future goal differential than Fenwick… however, Fenwick forms the basis for the most widely-used Expected Goals models.” Let’s use the same predictors in a correlation plot with Expected Goals percentage. Does Fenwick have the strongest correlation with xGoal percentage?</p>
<div style="page-break-after: always;"></div>
</div>
</div>
<div id="volleyball" class="section level2 hasAnchor" number="1.9">
<h2><span class="header-section-number">1.9</span> Volleyball<a href="exploratory-data-analysis.html#volleyball" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To begin, let’s go over some basic volleyball statistics. The following definitions come from <a href="www.rookieroad.com">www.rookieroad.com</a></p>
<ul>
<li>A <strong>Service Ace (SA)</strong> occurs when a player’s serve touches the ground on the other team’s side without being touched by a player on that side.</li>
<li>A <strong>Kill (K)</strong> occurs when a player gets the ball over the net without it being returned by the opponent.</li>
<li>An <strong>Assist (AST)</strong> is a pass made directly before a player makes a kill.</li>
<li><strong>Hitting Percentage (PCT)</strong> is the number of attempted kills (minus errors) divided by the total number of kill attempts. This helps determine how well a player or team is succeeding at their kill attempts.</li>
</ul>
<p>For Volleyball EDA, we will be using CSU Women’s Volleyball data from the last five seasons.</p>
<p>Let’s look at a scatter plot of hitting percentage and the number of digs. While no conclusions can be drawn from such a plot, it can give us some insight into relationships worthy of further analysis. Before creating the plot using the code below, think about what you might expect the outcome to be.</p>
<div id="scatter-plot-1" class="section level3 hasAnchor" number="1.9.1">
<h3><span class="header-section-number">1.9.1</span> Scatter Plot<a href="exploratory-data-analysis.html#scatter-plot-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="exploratory-data-analysis.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Digs, Hitting Percentage, Win/Lose</span></span>
<span id="cb95-2"><a href="exploratory-data-analysis.html#cb95-2" aria-hidden="true" tabindex="-1"></a>dig_pct_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> csu_vb, <span class="fu">aes</span>(<span class="at">x =</span> DIG, <span class="at">y =</span> PCT, <span class="at">color =</span> W_L)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb95-3"><a href="exploratory-data-analysis.html#cb95-3" aria-hidden="true" tabindex="-1"></a>dig_pct_viz</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Let’s change the axis titles, legend title, and add a main title.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="exploratory-data-analysis.html#cb96-1" aria-hidden="true" tabindex="-1"></a>dig_pct_viz <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Wins and Losses by Number of Digs and Hitting Percentage&quot;</span>,</span>
<span id="cb96-2"><a href="exploratory-data-analysis.html#cb96-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Number of Digs (DIG)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Hitting Percentage (PCT)&quot;</span>, <span class="at">color =</span> <span class="st">&quot;Win or Loss&quot;</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>What can we learn from this visual? Well, we can see that there is a weak linear relationship between the number of digs and hitting percentage. To an extent, hitting percentage decreases as the number of digs increases. Why is this the case? Maybe if a team has a really high hitting percentage, this means that the opposing team does not have as many opportunities to attack the other team offensively, reducing the number of opportunities for digs. It also seems that while wins and losses are somewhat evenly spread across the number of digs, there is a more clear cutoff for hitting percentage. It seems that the majority of wins are associated with a hitting percentage of at least 0.2, while the majority of losses are associated with a hitting percentage of less than 0.3.</p>
</div>
<div id="box-plot" class="section level3 hasAnchor" number="1.9.2">
<h3><span class="header-section-number">1.9.2</span> Box Plot<a href="exploratory-data-analysis.html#box-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now let’s take a closer look at the distribution of hitting percentage and digs for wins and losses. To do this, we will create box plots for each statistic.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="exploratory-data-analysis.html#cb97-1" aria-hidden="true" tabindex="-1"></a>pct_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> csu_vb, <span class="fu">aes</span>(<span class="at">x =</span> PCT, <span class="at">y =</span> W_L)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span>
<span id="cb97-2"><a href="exploratory-data-analysis.html#cb97-2" aria-hidden="true" tabindex="-1"></a>pct_viz</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="exploratory-data-analysis.html#cb98-1" aria-hidden="true" tabindex="-1"></a>dig_viz <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> csu_vb, <span class="fu">aes</span>(<span class="at">x =</span> DIG, <span class="at">y =</span> W_L)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span>
<span id="cb98-2"><a href="exploratory-data-analysis.html#cb98-2" aria-hidden="true" tabindex="-1"></a>dig_viz</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-28-2.png" width="672" /></p>
<p>Let’s modify these plots to make them more complete and visually appealing.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="exploratory-data-analysis.html#cb99-1" aria-hidden="true" tabindex="-1"></a>pct_viz <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Hitting Percentage for Wins and Losses&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Hitting Percentage (PCT)&quot;</span>,</span>
<span id="cb99-2"><a href="exploratory-data-analysis.html#cb99-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Win or Loss&quot;</span>) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;slateblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="exploratory-data-analysis.html#cb100-1" aria-hidden="true" tabindex="-1"></a>dig_viz <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Number of Digs for Wins and Losses&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Number of Digs (DIG)&quot;</span>,</span>
<span id="cb100-2"><a href="exploratory-data-analysis.html#cb100-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Win or Loss&quot;</span>) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;slateblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/unnamed-chunk-29-2.png" width="672" /></p>
<p>Box plots allow us to isolate each statistic (number of kills and hitting percentage) so we can more clearly determine the center and spread of each between wins and losses.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="current-tasks.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/aaron-nielsen/SportsAnalyticsBook/edit/master/01-eda.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["series.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
